### ISSUE TITLE
feat(format): add formatting linter

### ISSUE THREAD

**Issue by sergekh2** [JamieMason/syncpack#102]
Add -n, --dryrun option to format command and exit with 0 if there are no formatting changes, and 1 if formatting changes are required.

This will allow to check formatting in CI hooks and scripts.

**Comment by JamieMason** [comment]
Released in [12.3.0](https://github.com/JamieMason/syncpack/releases/tag/12.3.0).

👋 If anyone reading this finds syncpack useful, please tell people about it.

**Comment by fantua** [comment]
Hey, thanks for this feature! It would be nice mention format check in `lint` command docs:
- https://jamiemason.github.io/syncpack/command/lint/
- https://github.com/JamieMason/syncpack/blob/main/README.md
