### ISSUE TITLE
Please publish 8.4.10 to npm

### ISSUE THREAD

**Issue by codybrouwers** [JamieMason/syncpack#104]
## Description

Thanks for the great package! I'm setting it up and was trying to use the `isIgnored` feature but realized that 8.4.10 hasn't been published to npm yet. Could you get that pushed up when you get a chance?

Thank you!

**Comment by JamieMason** [comment]
It should be there now @codybrouwers 👍🏻 thanks.

**Comment by codybrouwers** [comment]
Awesome, thank you very much @JamieMason!
