### ISSUE TITLE
Unpublished internal packages with names matching public npm packages

### ISSUE THREAD

**Issue by Aghassi** [JamieMason/syncpack#107]
## Description

The detection logic has improved, and in some cases found more issues than I had before. That's a good thing. Don't ask me why, but one of our internal packages shares the name of an external npm package, but is not published. This means the check against the `name` field of the package.json will fail alignment if the `version` field is different. In our case, I found a project who's internal package name was `typescript` and the version was `0.0.1`. This failed the `typescript` alignment check which was already aligned.

For me, the immediate fix was just to rename the first party packages at no cost.

## Suggested Solution

I'm not sure there is a good solution here. Maybe I just need to change my configurations? Or the error could be improved to say something like "an internal package is named the same as an upstream package, is this your intention? If so do xyz. If not, consider renaming your internal package". 

It looks like the `versions` field is now checked where as before it might not have been

## Help Needed

I haven't looked at code, I'm just upgrading us and noticed this

**Comment by JamieMason** [comment]
I'm not sure what to do for this one @Aghassi, can you tell me more about the specific scenario you have? What % of syncpack users would you speculate might need this feature?

**Comment by JamieMason** [comment]
Also, disabling `--workspace` would disable checks against the local versions of packages developed in your monorepo.

**Comment by Aghassi** [comment]
I think this is definitely an edge case for sure. One way you could easily validate that something is the same as another package is to use the `homepage` field or other URL fields to validate. It is very unlikely that an internal package named the same as an upstream package would share (or have) that `homepage` field for example. Then you could categorize it as internal and not check it against upstream packages. I would say the % of users who hit this is VERY small. 

Thanks for the tip on the `--workspace` flag!

**Comment by JamieMason** [comment]
Going to close this one, if anything changes we can reopen it.
