### ISSUE TITLE
Allow using fix-mismatches to downgrade all, rather than upgrade all

### ISSUE THREAD

**Issue by Slapbox** [JamieMason/syncpack#110]
## Description

This would be a big help for times when you have to `git bisect` and some third-party dependency is the issue. `syncpack` makes our lives so easy when we're moving forward, but when we have to go backwards it's a rough time.

## Suggested Solution

A flag to always go to the lowest used version, rather than the highest, like `syncpack fix-mismatches --to-lowest`

## Help Needed
Pointers to where this code is handled now and where such a feature's code would belong in the repo.

## Alternative
Using Yarn's resolutions - but it's tedious to have to leave the command line during bisect.

Also, because we use `syncpack` in our `postinstall` step, when it throws an error it stops a command like `yarn && yarn start` with an error after `yarn` - which makes it tougher to use.

**Comment by JamieMason** [comment]
Thanks @Slapbox, the idea of choosing from various strategies I think would be a good idea. It's quite a big job so might be a while but I'd like to see this too.

**Comment by JamieMason** [comment]
Released in [9.8.4](https://github.com/JamieMason/syncpack/releases/tag/9.8.4).

Docs: https://jamiemason.github.io/syncpack/config/version-groups#preferversion-string

**Comment by Slapbox** [comment]
Wow that was so fast! Thanks @JamieMason!

**Comment by JamieMason** [comment]
You're welcome, let me know if it works as expected
