### ISSUE TITLE
bug: Cannot read properties of undefined (reading 'concat') at Option.collect

### ISSUE THREAD

**Issue by vonBrax** [JamieMason/syncpack#116]
## Description
Commands that use the source option seem to be throwing  this error:

TypeError: Cannot read properties of undefined (reading 'concat')
    at Option.collect [as parseArg] (...node_modules\syncpack\dist\option.js:38:21)

### Steps to reproduce:
```sh
npx  syncpack list-mismatches -s "packages/*/package.json"
```
env:
* syncpack: 9.0.0
* node: 19.4.0
* npm: 9.3.1
* os: windows 10

## Suggested Solution

Apparently the default/initial value for the `previous` parameter of the `collect` function was removed.
It was here: https://github.com/JamieMason/syncpack/blob/fa21deb3b31abc034ebff4885d2ffdf01d170b09/src/option.ts#L30-L35
And removed here: https://github.com/JamieMason/syncpack/blob/2cd34fd1f41e949cedd28b901a123906d8bc5d08/src/option.ts#L18-L22

Issue can be fixed by adding back this line:
https://github.com/JamieMason/syncpack/blob/fa21deb3b31abc034ebff4885d2ffdf01d170b09/src/option.ts#L34

**Comment by JamieMason** [comment]
Thanks @vonBrax I'll sort this today

**Comment by JamieMason** [comment]
Thanks for reporting, should be fixed in [9.0.2](https://github.com/JamieMason/syncpack/releases/tag/9.0.2)

**Comment by vonBrax** [comment]
Thank you for the awesome work and for the promptness in fixing the issue!
