### ISSUE TITLE
Syncpack deletes empty package.json nodes

### ISSUE THREAD

**Issue by tylerbutler** [JamieMason/syncpack#117]
## Description

In syncpack 9.0, empty nodes in package.json are removed. For example, we have a custom node in our package.json that looks like this:

```json
	"typeValidation": {
		"disabled": true,
		"version": "2.0.0-internal.2.1.0",
		"broken": {}
	}
```

We want to leave the empty `broken` field, but syncpack deletes it, even when no other package changes are needed. I think the change was in commit a279e56dfaf8ba11bd507a89315b2a5b038b027b.

## Suggested Solution

Ideally, syncpack would only edit fields it's supposed to, so I would expect it to only touch the dependency fields/types that it's configured to.

Alternatively, if the behavior could be disabled altogether, that would work for us, but not sure if that's the best general solution.

**Comment by JamieMason** [comment]
I'll undo that change, sorry about that.

**Comment by tylerbutler** [comment]
> I'll undo that change, sorry about that.

Thanks!
