### ISSUE TITLE
Complex semver versions are being replaced with ""

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/syncpack#119]
## Description

> One minor note: we use an unusual semver range for our in-workspace dependencies. For example, ">=2.0.0-internal.3.0.0 <2.0.0-internal.3.1.0". Unless I ignore these dependencies with an ignored versionGroup, syncpack overrwrites the versions with "". Maybe a bug, but could also be expected/undefined behavior since the version range is unusual.
> – https://github.com/microsoft/FluidFramework/pull/14042#discussion_r1107509804

## Suggested Solution

I'm not confident syncpack handles advanced versions like those very well at the moment, but it should leave alone anything it can't recognise as being valid semver, The bug will probably be in [`getHighestVersion(versions: string[]): string`](https://github.com/JamieMason/syncpack/blob/d397ea7d986815e3b5a79bcb017db83670839661/src/get-context/get-groups/version-group/instance-group/get-highest-version.ts#L5) which is called by [getExpectedVersion()](https://github.com/JamieMason/syncpack/blob/d397ea7d986815e3b5a79bcb017db83670839661/src/get-context/get-groups/version-group/instance-group/index.ts#L47).

## Help Needed

Creating a PR with a new [`./test/scenarios/*.ts`](https://github.com/JamieMason/syncpack/tree/d397ea7d986815e3b5a79bcb017db83670839661/test/scenarios) to reproduce this would be a help, then tests can be created and fixed from that.

**Comment by JamieMason** [comment]
I haven't reproduced this yet but it _may_ be fixed by https://github.com/JamieMason/syncpack/releases/tag/9.1.2, please give a try and let me know @tylerbutler, thanks.

**Comment by tylerbutler** [comment]
This does appear to be fixed, based on my testing! Note I tested with 9.3.2, though.

**Comment by JamieMason** [comment]
Great, I think this can be closed
