### ISSUE TITLE
feat(versions): support git tag versioned dependencies

### ISSUE THREAD

**Issue by samueljseay** [JamieMason/syncpack#125]
## Description

In https://github.com/woocommerce/woocommerce we use Syncpack, but recently made some changes to group a large set of `@wordpress` packages to git tag version numbers. e.g. `wp-6.0` for backwards compatibility support reasons. At that time I did that I didn't realise that Syncpack `fix-mismatches` doesn't support non-semver versions due to filtering the instanceGroup with `hasUnsupportedVersion`. So now when we run `fix-mismatches` it doesn't work.

## Suggested Solution

Would it be possible to have support for non-semver versions where basically all syncpack cares about is just overwriting the version string to match the one in syncpackrc?

For example if someone installs `@wordpress/keycode: 3.3.0` just blanketly replace it with ``@wordpress/keycode: wp-6.0`?

Perhaps an additional config value could be added to version groups like `ignoreSemver` or similar?

I'd be happy to make a contribution but would need some guidance on what kind of approach you'd prefer in that case.

**Comment by samueljseay** [comment]
@JamieMason sorry to bug you, but just wondering if you had thoughts about this. I'm happy to contribute a PR. Thanks!

**Comment by samueljseay** [comment]
Thanks @JamieMason that sounds like what we need! 🙇🏻

**Comment by JamieMason** [comment]
Released in [syncpack@10.0.0](https://github.com/JamieMason/syncpack/releases/tag/10.0.0), please let me know if you run into any issues.

**Comment by JamieMason** [comment]
@samueljseay git tags should be properly supported now without pinning them if you want to try it in https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0
