### ISSUE TITLE
v9 peerDependency check logic change debug issue

### ISSUE THREAD

**Issue by Aghassi** [JamieMason/syncpack#129]
Can you open a separate issue to discuss this one @Aghassi? You might be fine but I thought, since you just updated to v9 and that the shape of the configuration file changed in that version, that that change could be the reason why your project is no longer checking peer dependencies in the same way as you expected. If you share your config file in that issue I can take a look.

_Originally posted by @JamieMason in https://github.com/JamieMason/syncpack/issues/95#issuecomment-1538847541_

**Comment by JamieMason** [comment]
ok, for v9 and up you will need this config:

```diff
module.exports = {
+  dependencyTypes: ['dev', 'peer', 'prod', 'resolutions', 'overrides', 'workspace'],
-  dev: true,
  // Regex to filter what dependencies we care about.
  filter,
  indent: '  ',
-  peer: true,
-  prod: true,
-  resolutions: true,
-  overrides: true,
-  workspace: true,
  semverRange: '',
  sortAz: [
    'contributors',
    'dependencies',
    'devDependencies',
    'keywords',
    'peerDependencies',
    'scripts',
  ],
  sortFirst: ['name', 'description', 'version', 'author'],
  source: paths,
  versionGroups: [
    {
      isBanned: true,
      dependencies: banned,
      packages: ['**'],
    },
  ]
}
```

It looks like of the 7 [Default dependency types](https://jamiemason.github.io/syncpack/config/dependency-types#default-dependency-types) the only one you want to disable is `pnpmOverrides`, so we include all but that one in the array.

I was under the impression from https://github.com/JamieMason/syncpack/issues/95#issuecomment-1533443412 that you upgraded to v9 before writing your comments after that point, but here you mention this is your v8 config so I'm not sure. Bottom line, if you're on 8, stay as you are, when you move to v9 there was the breaking change we're discussing here which will need applying when you upgrade.

**Comment by JamieMason** [comment]
Please close if this makes sense, otherwise I'm happy to try and help some more.

**Comment by Aghassi** [comment]
Let me try this today. I have all those input in the v9 change, but I also had pnpmOverrides

**Comment by JamieMason** [comment]
What is the output you're expecting to see?

**Comment by Aghassi** [comment]
Doh I forgot I don't want this enforced on `peer`. I refactored and now it looks like when I run that command it passes as long as my config is 


```javascript
const config = {
  // Regex to filter what dependencies we care about.
  filter,
  indent: '  ',
  dependencyTypes: [
    'dev',
    'prod',
    'peer',
    'workspace',
    'resolutions',
    'overrides',
  ],
  semverRange: '',
  sortAz: [
    'contributors',
    'dependencies',
    'devDependencies',
    'keywords',
    'peerDependencies',
    'scripts',
  ],
  sortFirst: ['name', 'description', 'version', 'author'],
  source: paths,
  versionGroups: [
    {
      isBanned: true,
      dependencies: banned,
      packages: ['**'],
    },
    {
      dependencyTypes: ['dev', 'prod'],
      dependencies: ['@company/**'],
      packages: ['**'],
      pinVersion: 'workspace:*',
    },
  ],
}
```

However, I've also come across an interesting conundrum (which maybe is for the other thread). If you operate with pnpm and yarn while migrating, `yarn` can't resolve packages that call `workspace:*` as a resolution version.

But that's separate. This solution on dev seems to work.

**Comment by Aghassi** [comment]
@JamieMason can you cut me a new version on `main` that uses the `dev` changes but puts them behind a config flag? That will be easier for me because my build system is having issues pull from a git sha

**Comment by JamieMason** [comment]
could you build syncpack's dev branch locally and put the `dist` dir in a local `vendors/syncpack/` dir you check in temporarily? I've left the dev branch alone for you so it won't change. The newest branch I've been working on is the https://github.com/JamieMason/syncpack/compare/master...refactor branch - _another_ big refactor.

**Comment by JamieMason** [comment]
Is there anything I need to do on this one @Aghassi? 👍🏻

**Comment by Aghassi** [comment]
Yeah I'll close it. I'll figure out how best to build the branch. It's a shame I have to run a patch, but should be ok. I think my best bet is to patch the commit and patch syncpack via `pnpm patch`

**Comment by JamieMason** [comment]
```
git clone https://github.com/JamieMason/syncpack.git -b refactor
cd syncpack
yarn install
npm pack
```

Will create `syncpack-9.8.6.tgz`.

**Comment by JamieMason** [comment]
Just one polite nitpick – I don't think it's fair to say it's a _shame_ you have to run a patch – I don't know any projects out there cutting custom releases for one person. You can run a patch if you need this change _right now_, or you can wait for a busy guy doing his best to finish a big piece of work free of charge when he gets the time.

No hard feelings but I wanted to pick up on that.

**Comment by Aghassi** [comment]
Yes absolutely! I appreciate your work, that was not meant to put down all that you do. I'm trying v10 now internally and will get back to you.

**Comment by JamieMason** [comment]
it's all good 👍🏻
