### ISSUE TITLE
Output more info for syncpack lint

### ISSUE THREAD

**Issue by glomotion** [JamieMason/syncpack#134]
## Description

I'm currently implementing syncpack into our monorepo, and want to run it's `syncpack lint` command inside our cicd to checkover PR code. 

currently, when we run `syncpack lint`, it exits with 1 and the following:

```
> syncpack lint

-   7 package.json files
- 127 total dependences
-  55 in package.dependencies
-  70 in package.devDependencies
-   2 in package.version
Version mismatches
-  73 are valid
-   0 should have matching versions (prefer highest semver)
-   0 should have matching versions (prefer lowest semver)
-   0 should match workspace package version
-   0 are banned from use
-   0 should be pinned to a specific version
-   0 should snap to version used by another package
-   0 are filtered out
-   0 are ignored
-   0 have unsupported version format
Semver range mismatches
- 124 are valid
-   0 should use specific semver range
-   0 should use exact version in version property of package.json
-   0 are filtered out
-   0 are ignored
-   3 have unsupported version format
```

i'm guessing it's exiting with 1 because of the `3 have unsupported version format` but I have NFI what/where these are or how to fix them. Thus, this lint check isnt all that helpful RN. :( 

## Suggested Solution

Output details of the "3 have unsupported version format" items - so that we're able to fix them.

**Comment by JamieMason** [comment]
The lint command is only 2 days old and thanks for checking it out, your feedback helps improve it. 

Until now most people have been using both https://jamiemason.github.io/syncpack/lint-semver-ranges and https://jamiemason.github.io/syncpack/list-mismatches which do the same checks but with more detailed output.

I would use those for now and then let me know based on the other commands what kind of output would be best in your opinion for the new combined lint command. list is less verbose than list-mismatches for example, but also exits with an error code when needed.

**Comment by glomotion** [comment]
So yeah i assumed as much, and have swapped over to using list-mismatches just for now. 😁

So just out of interest, when i run: `npx syncpack lint-semver-ranges` - i get zero output but it still exit's as 1. 🤔 Is this expected?

![Screenshot 2023-05-31 at 3 11 28 pm](https://github.com/JamieMason/syncpack/assets/1452237/4c8099b6-9a32-4bec-b167-93b340b353af)

**Comment by JamieMason** [comment]
Looks like a bug, are you able to share the output of syncpack list?
