### ISSUE TITLE
Version 10.0.0 workspace for ranges

### ISSUE THREAD

**Issue by sfong23** [JamieMason/syncpack#136]
## Description
I saw that in version 10.0.0 that was just released the dependencyType `workspace` can be used to support version ranges. 

## Help Needed
How exactly can I add a range using `workspace` in my syncpack configuration file? For example, I want to ignore syncpack updates for `axios` versions that are `>= 0.3` but also `<1.0`. Did version 10.0.0 apply to #128 because that is what I am trying to do? Could you provide an example of what using `workspace` would look like in a configuration file for syncpack?

**Comment by JamieMason** [comment]
@sfong23 I just realised what you're referring to, that change to workspace was for https://github.com/JamieMason/syncpack/issues/124.

**Comment by JamieMason** [comment]
I'll close this but we can continue to discuss.

**Comment by sfong23** [comment]
Hello, is this now supported in version 10.5.1? If so would you be able to give an example of what using "sameRange" would look like in my case for a specific range?

**Comment by JamieMason** [comment]
Sure, of course. Is your repo public so I can get an idea of it?

**Comment by sfong23** [comment]
Unfortunately it is not but to get an idea here is the format: 

`versionGroups: [
  {
     "dependencies": ["axios"],
     "packages": ["**"],
     "isIgnored": true,
  }
]`

How would I use `sameRange` in my configuration so that `axios` is `>=0.3` but also `<1.0`?

**Comment by sfong23** [comment]
So just use `pinVersion`? Or will I still need `sameRange` in addition to that?

**Comment by JamieMason** [comment]
From what you've told me I _think_ the pinVersion approach is the most likely to give you what I think you're looking for - as far as I can tell so far.

That first code snippet you tried should change axios to always use the version `">=0.3.0 <1.0.0"` everywhere in your repo when you run `syncpack fix-mismatches`.

**Comment by sfong23** [comment]
Thank you that works!

**Comment by JamieMason** [comment]
Great, glad to help. If you have any other questions let me know.

**Comment by sfong23** [comment]
Hello, so with some testing I actually found that using `pinVersion` does not quite apply to what I am trying to do. For example I did `pinVersion: >=0.3.0 <1.0.0` but then if another package.json with `axios` had the dependency version of `0.4.0` this should be valid since it is within the range, but since it does not match exactly the string `>=0.3.0 <1.0.0` syncpack detects a mismatch. Do you know if what I am looking for is supported in syncpack or will be in the future?

**Comment by JamieMason** [comment]
No problem, I thought this might be the case. Yeah this doesn't exist yet, it sounds like some kind of clamping functionality. Please can you tell me as much as you can about your situation? Why things are the way they are and why this range functionality is needed? To help me build the right thing or get ideas for other similar things.

**Comment by sfong23** [comment]
I am working with a lot of different packages that have different package.json files. Some of these use the same dependencies but have different versions because that specific dependency version is needed for that package. So for example if I wanted to use version 3.0 for a certain dependency in one package, but then 6.0 in another then I'd want a range that allows versions >=3.0. Does that make sense?

**Comment by JamieMason** [comment]
For example 

1. Which versions of axios do you use?
2. Why do you use version x in package a but not package b? What is it about those packages and versions of axios that give them different needs?

I know it's a chore but the more I know the better help I can give you.

**Comment by JamieMason** [comment]
Update: There is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide now and a guide to [Local Package Versions](https://jamiemason.github.io/syncpack/guide/local-package-versions).
