### ISSUE TITLE
feat(source): handle negated globs in workspace configs

### ISSUE THREAD

**Issue by richburdon** [JamieMason/syncpack#139]
## Description

No apparent way to exclude globs from sources.
Additionally excluded patterns from `pnpm-workspace.yml` are ignored. E.g.,

```
packages:
  - `packages/**/*`
  - '!packages/skipped/**/*'
```

## Suggested Solution

Should honor exclusion globs (and provide --exclude CLI option)

## Help Needed

N/A

**Comment by richburdon** [comment]
Thanks for the quick response.

The issue is with a tool that is generating multiple temp directories that each have package.json files (this is happening inside one of the excluded pnpm package folders). There are a lot of collisions (between the templates and the workspace codebase) so it doesn't seem practical to add their dependencies to the ignored version group.

+1 for the ignore option.

**Comment by JamieMason** [comment]
Released in [10.6.1](https://github.com/JamieMason/syncpack/releases/tag/10.6.1). Any problems, please let me know. 

If you find syncpack useful, please star the project or help us spread the word to other Developers.
