### ISSUE TITLE
Seems to be unable to handle non-semver based version strings

### ISSUE THREAD

**Issue by wbern** [JamieMason/syncpack#14]
```
09:58 $ npx syncpack fix-mismatches --dev --indent "    "
(node:26719) UnhandledPromiseRejectionWarning: TypeError: Invalid Version: d
    at new SemVer (/home/user/Repos/project-fe/node_modules/semver/semver.js:312:11)
    at compare (/home/user/Repos/project-fe/node_modules/semver/semver.js:585:10)
    at Function.gt (/home/user/Repos/project-fe/node_modules/semver/semver.js:614:10)
    at /home/user/Repos/project-fe/node_modules/syncpack/dist/lib/version.js:41:20
    at Array.sort (native)
    at Object.exports.sortBySemver (/home/user/Repos/project-fe/node_modules/syncpack/dist/lib/version.js:19:10)
    at Object.exports.getNewest (/home/user/Repos/project-fe/node_modules/syncpack/dist/lib/version.js:6:26)
    at /home/user/Repos/project-fe/node_modules/syncpack/dist/fix-mismatches.js:68:44
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/user/Repos/project-fe/node_modules/syncpack/dist/fix-mismatches.js:66:58)
(node:26719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have a lot of "file:" protocol version strings, and some strings are links to github repos.. I suspect this is the issue, because I can run the command just fine without devDependencies.

I would really like to be able to run this tool on all my lerna packages.

**Comment by JamieMason** [comment]
Thanks a lot @wbern.

For anyone looking to pick this up, I think the files that will need updating are [/src/lib/version.ts](https://github.com/JamieMason/syncpack/blob/3.5.0/src/lib/version.ts) and [/src/lib/version.spec.ts](https://github.com/JamieMason/syncpack/blob/3.5.0/src/lib/version.spec.ts). Adding some new tests which feature other kinds of [version descriptors understood by npm](https://docs.npmjs.com/files/package.json#dependencies), then following the new failing tests should help reveal the affecting lines 👍

**Comment by JamieMason** [comment]
Please try with [3.5.2](https://github.com/JamieMason/syncpack/blob/master/CHANGELOG.md#352-2019-01-07) and let me know how you get on, thanks.

**Comment by JamieMason** [comment]
Please reopen if still an issue 👍

**Comment by JamieMason** [comment]
Update: [12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0) adds support for more version formats, such as Git URLs.
