### ISSUE TITLE
devDependency with non semVer value silently fails

### ISSUE THREAD

**Issue by jmatsushita** [JamieMason/syncpack#140]
## Description

I have this line in my `package.json`:
```json
  "devDependencies": {
    "@changesets/cli": "patch:@changesets/cli@npm%3A2.26.0#~/.yarn/patches/@changesets-cli-npm-2.26.0-49d5c5f72d.patch",
```

With it, `syncpack lint` fails silently (retuning exit code `1`), not showing anything sketchy even with `SYNCPACK_VERBOSE-true`

When removing it, everything works again. Note that I'm using yarn `4.0.0-rc.45` in case there's been some changes in the `patch:` protocol...

### Update

Any non semVer value [seems to fail](https://github.com/JamieMason/syncpack/issues/140#issuecomment-1585012389):
```json
{
  "devDependencies": {
    "a": "b"
  }
}
```

**Comment by jmatsushita** [comment]
I should add that this also happens when there's similar `patch:` values in the `resolutions` field.

Also a workaround is to `isIgnored: true` in `semverGroups` matching the dependency. In my example that would be:
```json
{
  "semverGroups": [
    {
      "packages": [
        "**"
      ],
      "dependencies": [
        "@changesets/cli"
      ],
      "isIgnored": true
    }
  ]
}
```

**Comment by jmatsushita** [comment]
Note that the syntax for resolutions has to include the `@version` suffix:
```json
{
  "semverGroups": [
    {
      "types": [
        "resolutions"
      ],
      "packages": [
        "**"
      ],
      "dependencies": [
        "@changesets/cli@^2.26.0"
      ],
      "isIgnored": true
    },
    {
      "packages": [
        "**"
      ],
      "dependencies": [
        "@changesets/cli"
      ],
      "isIgnored": true
    }
  ]
}
```

**Comment by jmatsushita** [comment]
Oh. There is a much simpler reproducer! In an empty folder with this `package.json`:
```json
{
  "devDependencies": {
    "a": "b"
  }
}
```

Running `npx syncpack lint` exits with status code `1` silently. Here's the log:
```bash
$ SYNCPACK_VERBOSE=true npx syncpack lint                                                                                 ~/dev/workshop/iios-syncpack
? readConfigFileSync( undefined )
? no config file found
? readFileSync( ...syncpack/package.json )
? readYamlFileSync( ...syncpack/pnpm-workspace.yaml )
? readFileSync(...syncpack/lerna.json )
? globSync( package.json )
? globSync( packages/*/package.json )
? Error: "glob" did not match "packages/*/package.json":
    at /.npm/_npx/be9d1b14e10e64b8/node_modules/tightrope/cjs/result/filter.js:12:23
    at /.npm/_npx/be9d1b14e10e64b8/node_modules/tightrope/cjs/result/lib/with-catch.js:9:20
    at curriedFn (/.npm/_npx/be9d1b14e10e64b8/node_modules/tightrope/cjs/fn/curry.js:7:20)
    at /.npm/_npx/be9d1b14e10e64b8/node_modules/tightrope/cjs/fn/pipe.js:5:36
    at Array.reduce (<anonymous>)
    at pipe (/.npm/_npx/be9d1b14e10e64b8/node_modules/tightrope/cjs/fn/pipe.js:5:16)
    at resolvePattern (/.npm/_npx/be9d1b14e10e64b8/node_modules/syncpack/dist/get-package-json-files/get-file-paths.js:26:36)
    at /.npm/_npx/be9d1b14e10e64b8/node_modules/syncpack/dist/lib/$R.js:18:32
    at /.npm/_npx/be9d1b14e10e64b8/node_modules/tightrope/cjs/fn/pipe.js:5:36
    at Array.reduce (<anonymous>)
? readFileSync( /...syncpack/package.json )
? add a@b to dev:versionsByName package.json
? add a@b to dev:versionsByName package.json
? exit( 1 )
```

**Comment by JamieMason** [comment]
I need to improve the output messaging to make it clearer what is happening (#132) but you _should_ only get an exit `1` when unsupported versions do not match each other. Could it be that `"@changesets/cli"` is not always `"patch:@changesets/cli@npm%3A2.26.0#~/.yarn/patches/@changesets-cli-npm-2.26.0-49d5c5f72d.patch"`? It's possible though that `syncpack lint-semver-ranges` is what's returning `1`, if you run eg `syncpack list` does that exit `0`? 

Since v10 syncpack will error on versions it considers invalid, but the messaging needs to improve to help understand and fix them. Downgrading to v9 should hopefully avoid this for now as it doesn't have this strictness.

**Comment by JamieMason** [comment]
Released in [10.6.1](https://github.com/JamieMason/syncpack/releases/tag/10.6.1). Any problems, please let me know. 

If you find syncpack useful, please star the project or help us spread the word to other Developers.

**Comment by jmatsushita** [comment]
Thank you, just tested it and it's a great improvement. I starred the repo too ⭐

**Comment by JamieMason** [comment]
Great 👍

**Comment by JamieMason** [comment]
Update: [12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0) adds better support for non-semver version formats and there is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide. The output when there are errors should also be more detailed now too.
