### ISSUE TITLE
Feature Request: Ignore mismatches in default versionGroup.

### ISSUE THREAD

**Issue by xenobytezero** [JamieMason/syncpack#141]
## Description

As I gradually roll out syncpack to my whole monorepo, it would be really useful to only apply fixes to dependencies determined by my specific versionGroups in the config file, essentially ignoring everything in the "default" version group.

## Suggested Solution

A switch or config item that would ignore everything in the default version group.

**Comment by JamieMason** [comment]
Hey there, you should be able to do this by making the last group match everything and be an `isIgnored` group

```
{
  "versionGroups": [
    {
      "packages": ["**"],
      "dependencies": ["**"],
      "isIgnored": true
    }
  ]
}
```

And the same for semver groups if needed.

https://jamiemason.github.io/syncpack/config/version-groups/ignored

**Comment by xenobytezero** [comment]
Didn't think of that as an option, works exactly how I want it to. Thanks!

**Comment by JamieMason** [comment]
Great 👍
