### ISSUE TITLE
syncpack fix-mismatch not working in v10 latest

### ISSUE THREAD

**Issue by andrew-hm** [JamieMason/syncpack#143]
## Description

`syncpack fix-mismatches --types dev,prod,workspace` works as expected in 9.8.6 but not 10 or 10.6.1.

This [example from the doc](https://jamiemason.github.io/syncpack/config/dependency-types#the-workspace-type) doesnt work in v10, but does in 9. I have a similar setup, monorepo, with one workspace under packages/ directory that has a new version. another workspace under packages/ references it, but when running fix-mismatches it is not changing the version as expected to match what's in the package.json. this works in v9.8.6 though. i even got fancy with it. thought that because the dependent listed it with a caret that maybe that's why it wasn't changing it. nope. even if its a pinned version, which you would expect to have to change to reflect value in package.json, it didnt work either. only v9 does.

**Comment by JamieMason** [comment]
Thanks @andrew-hm I'll take a look.

**Comment by JamieMason** [comment]
Released in [10.7.3](https://github.com/JamieMason/syncpack/releases/tag/10.7.3). Any problems, please let me know. 

If you find syncpack useful, please star the project or help us spread the word to other Developers.
