### ISSUE TITLE
Question: Using version groups to have different version policies for the same dependency

### ISSUE THREAD

**Issue by jcksonhe** [JamieMason/syncpack#145]
## Description

Here's our use case: We have a monorepo with a package.json at the root with all the lib versions we want. Under packages/ is a bunch of packages with their respective package.jsons where we want to use `*` as the version for common libs so that it takes from the root package.json. This is so that when we upgrade common libs, it doesn't require a change in the packages' package.json and rope in reviewers for those packages.

However, if I use syncpack's `list-mismatches`, it'll want me to use `*` as the version in the root as well, since `*` is considered the "highest" version in use:
![image](https://github.com/JamieMason/syncpack/assets/8689181/260e1074-ca93-4b1c-a1e8-c2049193bcfe)

I tried using the "sameRange" `policy` following [this example](https://jamiemason.github.io/syncpack/config/version-groups/same-range), but no luck either.

Can this be supported through "sameRange"? Of course, there's the possibility I missed something in the documentation so if this is already supported, please let me know!

## Suggested Solution

If "sameRange" is specified as the `policy`, don't warn on a specific, consistent version used elsewhere in one or multiple package.jsons

## Help Needed

Not sure, but if this is not currently supported, I'd be happy to take a deeper look :)

**Comment by JamieMason** [comment]
Assuming a monorepo with `root`, `foo`, and `bar`, creating a version group _should_ do this for you:

```json
{
  "versionGroups": [
    {
      "dependencies": ["common-lib-one", "common-lib-two"],
      "packages": ["foo", "bar"],
    }
  ]
}
```

What we're doing is creating a partition which includes the packages but doesn't include the root, just for the common/shared libs we're interested in. 

Please see:

- https://jamiemason.github.io/syncpack/guide/version-groups
- https://jamiemason.github.io/syncpack/config/version-groups

You could add [`pinVersion: '*'`](https://jamiemason.github.io/syncpack/config/version-groups/pinned) to that group if you wanted to always force the version within those packages to be `*`.

**Comment by JamieMason** [comment]
Another option is a [Snapped To](https://jamiemason.github.io/syncpack/config/version-groups/snapped-to) group, which would cause the `foo` and `bar` packages to copy whatever value `root` is using. It wouldn't be DRY like you're wanting, but there would be a single source of truth and syncpack would push the values from root to the packages whenever they change.

**Comment by jcksonhe** [comment]
It works - thank you very much!!
Also, please consider including a code of conduct in this project. It would allow us to nominate this project for funding :)

**Comment by JamieMason** [comment]
You're welcome, and thank you for the note on adding a CoC.
