### ISSUE TITLE
docs(misc): monorepo article feedback

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/syncpack#150]
## Discussion

In response to https://github.com/vercel/turbo/issues/2060#issuecomment-1649598155 by @jtlapp. Thanks so much for including syncpack in your article, I thought I'd reply/feed back over here so as to not clutter that thread.

---

1\. 

> Syncpack’s handling of workspaces is a bit odd. If we add workspace dependencies as "workspace:*", Syncpack won't be able to compare the versions we're using and will treat all workspace dependencies as having mismatched versions. The simplest solution is to tell Syncpack to ignore workspace versions by adding the following .syncpackrc.json file to the monorepo root (yes, it’s counterintuitive)

Totally agree here, the [workspace dependency type](https://jamiemason.github.io/syncpack/config/dependency-types#the-workspace-type) is the most confusing aspect of syncpack. What I've struggled with is that "workspace" is a pretty overloaded term and refers to quite a few things. I've used it to refer to your own packages developed in your own monorepo. 

I could fix this as a breaking change in a future version, the least worst alternative I've thought of is referring to them as "local" dependencies instead, but I'm not sure, that could clash with `file:` and `link:` dependencies possibly. Any ideas or feed back more generally would be a great help.

2\.

> ```jsonc
> // root .syncpackrc.json
> {
>   "workspace": false
> }
> ```

FYI this configuration changed in version [9.0.0](https://github.com/JamieMason/syncpack/releases/tag/9.0.0).

3\.

> Finally, to make all the package versions consistent, do the following, which appears to change all versions to the greatest version found for each package (I can’t find an official explanation in the documentation)

That's correct, by default the highest valid semver version is used. This can be changed to the lowest version via the [`preferVersion`](https://jamiemason.github.io/syncpack/config/version-groups/standard#preferversion-string) option which is very hard to find in the docs, I'll try to improve that.

---

Thanks again, your section has helped me think of ways to improve this tool, and help others learn about it.

**Comment by jtlapp** [comment]
Thank you so much! I tried out the latest changes and updated the [instructions for v9.0.0+](https://javascript.plainenglish.io/sharing-typescript-with-nx-and-turborepo-part-4-managing-a-monorepo-a48adc99823e#77b7).

Your utility is a life saver. Without it, I'm not sure how we'd be managing monorepos.

**Comment by JamieMason** [comment]
Closing as these issues should hopefully now be addressed.

The workspace dependency type is now referred to as [the local dependency type](https://jamiemason.github.io/syncpack/guide/local-package-versions/#the-local-dependency-type).

To anyone reading this, please feel free to open issues for anything you find which could be made clearer.
