### ISSUE TITLE
Add "any allowed" semverRange setting

### ISSUE THREAD

**Issue by xenobytezero** [JamieMason/syncpack#159]
## Description

I would like to use `syncpack lint` on my CI, but I'm not too worried about the multiple differing `semvarRanges` (at least not right now).

It would be good if syncpack could be configured to ignore mismatches in `semverRanges` and only lint the version numbers when `lint` is used.

**Comment by JamieMason** [comment]
Running list-mismatches instead will do this for you 👍

**Comment by xenobytezero** [comment]
Ahh ok, does it still do the same exit codes as `lint` so that it will fail a CI check if the versions mismatch?

**Comment by JamieMason** [comment]
It does, all `lint` pretty much does is [run `list-mismatches` and then `lint-semver-ranges` together](https://github.com/JamieMason/syncpack/blob/main/src/bin-lint/lint.ts#L21-L23), but those commands when run alone also exit with the appropriate exit code.

**Comment by xenobytezero** [comment]
Excellent, thank you!

**Comment by JamieMason** [comment]
You're welcome 👍

**Comment by JamieMason** [comment]
Update: [12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0) can now fix version mismatches while leaving semver ranges alone, it's mentioned in the new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide.
