### ISSUE TITLE
feat(cli): add option to list every dependency usage without deduping the version

### ISSUE THREAD

**Issue by audunolsen** [JamieMason/syncpack#162]
## Description

An option to list all dependencies that are listed in two or more workspace packages, regardless of the version mismatch state.
Running `syncpack list-mismatches` shows all mismatched versions which is great. these can all be autofixed. Syncpack does not however aid you in knowing all packages which are **prone** to mismatching. When authoring syncpack config it is difficult to know what packages to include in the `versionGroups` field. You may have dependencies used in multiple workspace packages that already have matched versions, **these** should be included in the syncpack config as they are prone to mismatching, but they are hard to identify through manually scanning multiple `package.json` files.

## Suggested Solution

A CLI option to show either
1. All repeated dependencies regardless of mismatch state (easiest to implement)
2. All repeated dependencies currently not covered in config's `versionGroups` field. (most helpful but more complex implementation)

CLI commands could look something like
`$ syncpack list --repeated` (all repeated packages)
`$ syncpack list --repeated --uncovered` (not covered by config)

---

(Syncpack is amazing 🔥)

**Comment by JamieMason** [comment]
Thanks @audunolsen,
I see what you mean – if you run `syncpack list` and you use `concurrently` in 4 packages, but they all have the same version, all you will see in the output is:

```
- concurrently ^8.0.1
```

Even something like this might be an easy addition

```
- concurrently ^8.0.1 (used 4 times)
```

But people might not want that by default. I would quite like some way to let people choose different output formats, or even offer a way for people to install and use custom 3rd party plugins, but that's a little way off yet.

**Comment by JamieMason** [comment]
So far I've decided to change the default output of `syncpack list`. The next release is going to take a while, but it'll be something like the below.

This is from my local build:

<img width="421" alt="new syncpack list" src="https://github.com/JamieMason/syncpack/assets/320492/d2639d09-3750-424b-9d83-e9d09bcdedf0">

Thanks for the idea @audunolsen, I think this is much better.

**Comment by JamieMason** [comment]
Released in [12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0)
