### ISSUE TITLE
How to sync monorepo package versions?

### ISSUE THREAD

**Issue by Zamiell** [JamieMason/syncpack#166]
Hello, and thanks for the excellent tool.

I love syncpack! I use it a lot to propagate new deps from the monorepo root package.json file downward into the child package package.json files.

However, one thing syncpack does not do is update versions that are not installed in the package root. In other words, consider a pretty typical monorepo with packages `foo` and `bar`, which would look like this:

```
monorepo/
├── package.json
└── packages/
    ├── foo/
    |   └── package.json
    └── bar/
        └── package.json
```

We can imagine that `foo` is dependent on `bar`, version 0.0.1.
But then we update `bar` to version 0.0.2.
So now the "monorepo/foo/package.json" file needs to be updated, but syncpack doesn't do this, because `bar` is not installed at the root of the monorepo.

So it would be nice if syncpack had some option or command to look through monorepo packages in "packages" folder and then through all the other packages to see if they depend on it and need updating.

**Comment by JamieMason** [comment]
Hey @Zamiell, thanks a lot. 

Could you create a throwaway repo which is a minimal reproduction please? I'm pretty sure syncpack can do this today but I'd need to see how you have it configured. Then I'll be able to show you what to change, or reproduce some bug if there is one.

Thanks.

**Comment by Zamiell** [comment]
Ah, I see now, syncpack already has this feature!

When creating a minimal reproduction, I see that it does automatically update `bar` to "0.0.2" when running the `npx syncpack fix-mismatches` command.

However, there are two bugs that I can see. I have created a reprex repository that showcases these bugs:
https://github.com/Zamiell/test-monorepo

## Clone it:

```
git clone git@github.com:Zamiell/test-monorepo.git
cd test-monorepo
npm install
```

## Bug 1

```
npx syncpack fix-mismatches
git diff
git reset --hard
```

Notice that the "^" prefix character was blown away. This is a bug. `syncpack` should not blow away the "^" character, it should preserve it.

## Bug 2

```
npx syncpack fix-mismatches --types prod,dev
git diff
```

Notice that even though "bar" is a production dependency, `syncpack` does not sync it.

**Comment by Zamiell** [comment]
@JamieMason Thank you! It looks like the magic word of "local" worked. This magic word [seems to be undocumented](https://jamiemason.github.io/syncpack/fix-mismatches). Can we update the documentation please?

Secondly, I have a question about the design of this. [According to the npm manual, there are only five types of dependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json):

- dependencies (production)
- devDependencies
- peerDependencies
- bundleDependencies
- optionalDependencies

And then, it was my understanding that the `--types` flag corresponded to these 5 types. For example, in my use-case, I wanted to exclude "peerDependencies" + "bundleDependencies" + "optionalDependencies", so I knew that I should specify "--types prod,dev" in order to sync only the dependencies in the first two categories.

But it seems that my mental model about this flag is wrong, because "local" does not correspond to any of these 5 categories. Subsequently, I think it is confusing to have to use a "local" keyword here. In other words, since the "bar" dependency exists inside of the "prod" (i.e. "dependencies") field, then I naively expect it to be synced by specifying "--types prod" without having to specify anything additional.

**Comment by JamieMason** [comment]
Yep 👍 one reason this next release has taken months and counting is that the documentation is a huge job. It'll come in the next few weeks hopefully but syncpack is an unfunded one man project done in my spare time. There is some mention of local in the docs but more will come.

**Comment by JamieMason** [comment]
[12.0.0-alpha.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0-alpha.0) was just released today and with it is an overhaul to the documentation.

There is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide and [Local Package Versions](https://jamiemason.github.io/syncpack/guide/local-package-versions) guide which aim to improve understanding around some of the things we've discussed.

**Comment by Zamiell** [comment]
Very cool, thank you! Should I close this issue now?

**Comment by JamieMason** [comment]
If everything works as expected now then yeah we're good to go 👍
