### ISSUE TITLE
typescript config file

### ISSUE THREAD

**Issue by adnjoo** [JamieMason/syncpack#169]
## Description

add e.g. `.syncpackrc.ts` option for config file

## Suggested Solution

pros - types

cons - work needed

## Help Needed

read/compile typescript file?

write types file out?

**Comment by JamieMason** [comment]
Hi. This would be an issue for https://github.com/cosmiconfig/cosmiconfig, which syncpack uses.

**Comment by adnjoo** [comment]
hmm ok thank u!
