### ISSUE TITLE
fix(cli): make status codes easier to read

### ISSUE THREAD

**Issue by gtjamesa** [JamieMason/syncpack#172]
I'm just testing the 12-alpha to use the `$LOCAL` setting for my local monorepo packages. I love the new output layout, but the colours are pretty hard to read. 

I'm using the [crcandy](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#crcandy) zsh theme with the default Terminal on Linux Mint 21. The main terminal colours are coming from the system theme, but I switched to a few different dark themes and still had trouble viewing the `[PinnedMismatch]` text

![image](https://github.com/JamieMason/syncpack/assets/2078364/9988f867-0119-41a9-8d72-19bf3abfd1e7)

**Comment by JamieMason** [comment]
Thanks @gtjamesa, I'll see about tweaking those. With the status codes being something I felt would be read the least often I think I set them to both grey AND dimmed. I did have a hunch this would come back and bite me but it looked pretty nice in my theme. Happy to make a change 👍

**Comment by gtjamesa** [comment]
Great thanks! Yeah, I totally understand where you're coming from, and I'm sure someone will always have a problem with some colours. I've just been tweaking my terminal theme now, so it's more visible anyway

**Comment by JamieMason** [comment]
Great, thanks. In the future I could maybe move the colours out into config so they can be overridden, shouldn't be too hard.

**Comment by JamieMason** [comment]
See how it looks in v12 @gtjamesa, I've changed them to blue.

**Comment by gtjamesa** [comment]
Sorry for the delay - I just updated it, and it looks great. Thank you!

**Comment by JamieMason** [comment]
You're welcome 👍
