### ISSUE TITLE
Question on using $LOCAL in a semver group

### ISSUE THREAD

**Issue by mctrafik** [JamieMason/syncpack#176]
## Description

I'm trying to do:

```
  semverGroups: [
    {
      label: 'Use caret (^) ranges for non-local deps',
      range: '^',
      dependencyTypes: ['prod', 'dev', 'resolutions', 'overrides'], // Not 'peer', not 'local'
      dependencies: ['**'],
      packages: ['**'], 
    },
  ],
```

But I keep getting errors like:

```
✘ @my-local-package1.0.0 → ^1.0.0 in dependencies of another-local-package/package.json
```

## Suggested Solution

Would love to do:

```
dependencies: ['!$LOCAL'],
```

## Help Needed

If there's another way to achieve this, please lmk.

**Comment by JamieMason** [comment]
Looks good to me @mctrafik.

I'll confirm for you to check it matches what you expect, your most recent example will do this:

- for every package in the monorepo.
- for every part of package.json files except peerDependencies.
- when the name of the dependency is one of the packages developed in this monorepo.
- use an exact version number.
