### ISSUE TITLE
feat(update): add repository url to the prompt

### ISSUE THREAD

**Issue by auto200** [JamieMason/syncpack#178]
## Description

When updating packages i find myself constantly searching for the package repositories/release notes to see what changes have been made. This is pretty tedious and repetitive

## Suggested Solution

I would like to have link to the package repository next to the update prompt, that way I can just click and open directly in the browser. Option to show/hide this additional information could be configured by setting in the config

![image](https://github.com/JamieMason/syncpack/assets/49625375/73617381-9e66-4f05-80d3-508c4ed920ed)

I've made a quick draft https://github.com/JamieMason/syncpack/pull/177

**Comment by JamieMason** [comment]
Released in [12.0.0](https://github.com/JamieMason/syncpack/releases/tag/12.0.0), thanks.
