### ISSUE TITLE
feat(cli): throw when an entered command is invalid

### ISSUE THREAD

**Issue by ChristopherChudzicki** [JamieMason/syncpack#179]
## Description

I've just started using `syncpack`—a great tool for its job! Being new and forgetful, I run `npx syncpack list-mismatch` (instead of the pluralized `list-mismatches`). Instead of erroring, the CLI behaves as if I had run `npx syncpack` with no subcommand.  This caused me a little confusion.

## Suggested Solution

Running `npx syncpack <SUBCOMMAND>` should error (and maybe show the `--help` message) if `<SUBCOMMAND>` is not valid.

## Help Needed

Do maintainers agree this is a desirable change? *I **very** briefly looked in the implementation and saw the CLI is made with `commander`. I've used commander and am mildly confused about its behavior here since my experience has been that it errors on undefined subcommands. Likely I missed some detail of the implementation here.*

**Comment by JamieMason** [comment]
Thanks @ChristopherChudzicki, 
Writing from my mobile just now, if you want to try it the V12 alpha should have a fix for this. 

Please let me know if you hit any issues

```
npm install -g syncpack@alpha
```

**Comment by ChristopherChudzicki** [comment]
Works great!

```
npx syncpack@alpha list-mismatch
error: unknown command 'list-mismatch'
(Did you mean list-mismatches?)
```

This seems resolved to me, though not sure if you close issues on release or implementation.

Thanks again!

**Comment by JamieMason** [comment]
Great, thanks a lot for the detailed issue @ChristopherChudzicki.

> This seems resolved to me, though not sure if you close issues on release or implementation.

Yeah good point, I'll wait on closing this until v12 is out of alpha and in `syncpack@latest`.

**Comment by JamieMason** [comment]
v12 is out of alpha
