### ISSUE TITLE
[dependency maintenance] @effect/match -> effect migration

### ISSUE THREAD

**Issue by ari-becker** [JamieMason/syncpack#181]
## Description

a) proximate trigger: unmet peer dependency in syncpack 12:

```text
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ syncpack 12.0.0
  └─┬ @effect/match 0.40.0
    └── ✕ unmet peer effect@2.0.0-next.47: found 2.0.0-next.62
```

I see that `0.40.0` is indeed the latest version of `@effect/match`:
![image](https://github.com/JamieMason/syncpack/assets/1388505/227f0dba-a3f4-4c91-8551-79fe39ba0fd2)

However, the package links to a repository which has been archived:

![image](https://github.com/JamieMason/syncpack/assets/1388505/a7889010-1c3d-4003-b10d-a2ca4948501d)

Apparently there was some kind of migration, Effect now recommends `import { Effect } from "effect"` and `Effect.match`:

https://www.effect.website/docs/error-management/matching

## Suggested Solution

Follow upstream changes to solve the peer dependency issue?

## Workaround

`package.json`:

```json
{
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "@effect/match@0.40.0>effect": "2.0.0-next.62"
      }
    }
  }
}
```

**Comment by JamieMason** [comment]
I've switched this repo over to using pnpm strict, hopefully this is resolved in [12.0.1](https://github.com/JamieMason/syncpack/releases/tag/12.0.1)
