### ISSUE TITLE
fix(workspace): add support for workspace:^

### ISSUE THREAD

**Issue by belgattitude** [JamieMason/syncpack#182]
First of all thanks for your work :)

## Description

Tried an upgrade from v11 latest to v12.0.1 and there's an error regarding workspace:^

See https://github.com/belgattitude/httpx/pull/819

```bash
yarn install
yarn syncpack lint-semver-ranges --types prod,dev --source "package.json" --source "packages/*/package.json"
```

Will print

```
✘ name @httpx/exception or version workspace:^ are not supported packages/json-api/package.json > dependencies [UnsupportedMismatch]
```

**Comment by JamieMason** [comment]
Thanks @belgattitude, will take a look. I don't know if this is a regression though as `workspace:^` has not been knowingly supported before - how did this behave for you prior to V12?

**Comment by belgattitude** [comment]
Probably working before or the exit code wasn’t informing an error. At least you’ll see the ci failing after the upgrade. Passed before

**Comment by JamieMason** [comment]
Released in [12.1.0](https://github.com/JamieMason/syncpack/releases/tag/12.1.0).

👋 If anyone reading this finds syncpack useful, please tell people about it.

**Comment by belgattitude** [comment]
Thanks a lot, just tested and it seems to work. Great job and happy new year !

**Comment by Mearman** [comment]
Just stumbled on this thread. I'd like to pin of my workspace deps to "workspace:^" but I've not been able to get it to accept it. do you have a sample of how it SHOULD be done?

**Comment by JamieMason** [comment]
Sure, please open a new issue with info on your current config, syncpack version, what you've tried and expect to happen etc. and I'll help you out.
