### ISSUE TITLE
fix(local): allow missing .version if not depended on

### ISSUE THREAD

**Issue by keyz** [JamieMason/syncpack#183]
## Description

According to [the npm spec](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#version), it's fine to omit the `version` field in package.json:

> If you don't plan to publish your package, the name and version fields are optional

Omitting the `version` field is common for leaf packages that won't ever be published, such as "apps" in a monorepo. IMO this change (introduced by v12) feels like a regression.

Here's a simple repro. The following `package.json` declares a private package ("app"):

```json
{
  "name": "my-express-app",
  "private": true,
  "scripts": {
    "repro": "syncpack list-mismatches"
  },
  "devDependencies": {
    "syncpack": "^12.0.1"
  }
}
```

```bash
$ npm run repro

> repro
> syncpack list-mismatches

= Default Version Group ========================================================
✘ my-express-app PACKAGE_JSON_HAS_NO_VERSION → ??? package.json > version [MissingLocalVersion]
  package.json does not have a .version property which is exact semver
     1 ✓ already valid
     1 ! can be fixed manually using syncpack prompt
```

## Suggested Solution

Relax the policy such that leaf packages (that no one depends on) can omit the `version` field

**Comment by JamieMason** [comment]
Thanks I'll check it over, it should only happen if it is depended on.

https://jamiemason.github.io/syncpack/guide/status-codes/#missinglocalversion

**Comment by dbrxnds** [comment]
Running into this same issue now as well.

**Comment by JamieMason** [comment]
I would stay on v11 for now if this is an issue.

**Comment by JamieMason** [comment]
Released in [12.1.0](https://github.com/JamieMason/syncpack/releases/tag/12.1.0).

👋 If anyone reading this finds syncpack useful, please tell people about it.

**Comment by bitofbreeze** [comment]
Is there a way to not require a version for all private packages?

**Comment by JamieMason** [comment]
A brief answer as I'm traveling right now but the latest version at https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.1 will warn on missing local versions but otherwise let you continue. Let me know if you need something more than this.
