### ISSUE TITLE
fix(cli): include names of ignored packages

### ISSUE THREAD

**Issue by wyozi** [JamieMason/syncpack#184]
## Description

Hi! I'm gradually integrating syncpack into a project and have chosen to do it by enabling packages one-by-one. It would be nice to optionally see the list of ignored packages when using `syncpack list` (like v11 used to show)

## Suggested Solution

Add a flag to `syncpack list` to explicitly list ignored packages too

**Comment by JamieMason** [comment]
Released in [12.1.0](https://github.com/JamieMason/syncpack/releases/tag/12.1.0).

👋 If anyone reading this finds syncpack useful, please tell people about it.
