### ISSUE TITLE
question(rcfile): how to require a shared configs package?

### ISSUE THREAD

**Issue by clabnet** [JamieMason/syncpack#186]
Hi, 
in a pnpm monorepo I would run a command as is:
`"syncpack:fix": "cross-env SYNCPACK_VERBOSE=true syncpack format --config @me/configs-syncpack/syncpack.json" `
but the config file is not found and default config is used.

How to get the config file from a package ? 
Thanks in advance

**Comment by JamieMason** [comment]
Hey @clabnet,
If you create a .syncpackrc.js file similar to how this project has done:

https://github.com/muravjev/configs/blob/9b323d300b03f7bbeb4eabc85cdbbdbe51b37b56/.syncpackrc.js#L1

So in your case

```js
module.exports = require('@me/configs-syncpack/syncpack.json');
```

You can remove the `--config` option like so:

```diff
- "syncpack:fix": "cross-env SYNCPACK_VERBOSE=true syncpack format --config @me/configs-syncpack/syncpack.json"
+ "syncpack:fix": "cross-env SYNCPACK_VERBOSE=true syncpack format"
```

and it should hopefully all work as expected.

**Comment by clabnet** [comment]
@JamieMason It work fine. Thank you.
