### ISSUE TITLE
question(core): can syncpack manage tsconfig.json files?

### ISSUE THREAD

**Issue by clabnet** [JamieMason/syncpack#187]
Hy @JamieMason, 
thanks for this formidable package.

Have you provided to replicate similar functions to reorganize in intelligent mode also the tsconfig.json file ?

**Comment by JamieMason** [comment]
Hi @clabnet, thanks a lot.

Syncpack only touches package.json files, what kinds of functionality are you thinking about which involves tsconfig.json files?

**Comment by clabnet** [comment]
When we compare similar tsconfig.json(s) we have always the same problem to compare different values for the same key, and and the order of the keys can be useful.  Others packages are created for this use :
- https://www.npmjs.com/package/eslint-config-sort-tsconfig 
- https://github.com/p-chan/sort-compiler-options 
....
 This is the official reference : https://www.typescriptlang.org/tsconfig
 but you surely already know it ... 
 
 Thanks @JamieMason

**Comment by JamieMason** [comment]
Ok I see what you mean now. I see the similarities but I don't think it would be a good fit for this project, at least at the moment. Let me know if I'm missing anything 👍
