### ISSUE TITLE
question(core): should syncpack bump package versions after fixing mismatches?

### ISSUE THREAD

**Issue by duytan-hoang-eurostar** [JamieMason/syncpack#188]
## Description

After running `fix-mismatches`, should any modified packages have their version number updated with a `patch`? As the package has been updated

```
{
  "name": "my-package",
  "version": "1.0.0", // bump to 1.0.1
  ...
  "dependencies": {
    "react": "18.2.0" // updated from 18.1.0
  }
  ...
}
```

## Suggested Solution

Not sure if there's a reason why this isn't the behaviour, but perhaps it could be an option? Would also be good if the option also allowed for the version to be formatted. Allowing things such as appending (e.g. `1.0.1-beta`)

**Comment by JamieMason** [comment]
Thanks for the question Duytan.

I think this falls just slightly outside the scope of syncpack. It's not common to change lots of npm dependencies and then cut a release for publishing immediately, usually syncpack would be run as part of general housekeeping or linting then committed as a change on its own.

This would be tested and then other commits might accumulate such as features or bug fixes etc which are also tested, then once everything passes yo would then cut a release – it's at _that_ time that the version number of your own packages would tend to be bumped.

(The Syncpack project uses [release-it](https://github.com/release-it/release-it) for this by the way, which is excellent. There are other similar tools too.)

It's possible to create an npm script/build step/workflow/etc of your own which runs syncpack and cuts a release if anything changed, if that's what your wanted to do, but I don't think it is something that should be made part of syncpack itself. 

The principle behind my thinking is that syncpack should focus on doing one thing well, then people can slot that in wherever they want to as one step of a bigger workdlow.

Sound fair? Let me know what you think, thanks.

**Comment by JamieMason** [comment]
There is #48 which discusses a Node API, but FYI it's pretty much blocked at the moment, until I hear a good mix of use cases and when and how it would be used. I don't know what the requirements are for it so right now there's not a good justification for doing it. Plus the codebase of syncpack has been changing a lot as people have reported new feature requests or use cases etc. so I'd like it to have stabilised before having to support a Node API.
