### ISSUE TITLE
question(config): how to pin local packages to "workspace:*"? (2)

### ISSUE THREAD

**Issue by clabnet** [JamieMason/syncpack#192]
## Description

On a pnpm monorepo I have dependency as `"@pomini-apps/shared": "workspace:*",`
that point at package with the current version on the workspace.
Maintain the assignment `"workspace:*"' is useful to avoid frequently changes to version number. 

## Suggested Solution

For this case don't change the version as current dependency version, but maintain the assignment "workspace:*"

Before `syncpack fix` command:
![image](https://github.com/JamieMason/syncpack/assets/6067610/277a6c4c-de26-4f2f-ab0b-42b3aac23b40)

After `syncpack fix` command:
![image](https://github.com/JamieMason/syncpack/assets/6067610/5ce9cd8e-18a1-4b0f-bf35-02d97bfd11ce)

Thank's

**Comment by KeKs0r** [comment]
This still works on version `11.2.1` . So it seems to be a bug introduced afterwards.

**Comment by clabnet** [comment]
I can confirm this behaviour on v12.3.0.

**Comment by JamieMason** [comment]
Thanks both, yes this is a regression in v12. I'm a bit surprised as I added a test for this scenario [1] after it had happened in a previous version, obviously I've missed something and this is a new scenario I don't have covered.

Will it be easy to reproduce? What can you tell me about your situations?

[1] https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/version-group/standard.spec.ts#L2212-L2289

**Comment by JamieMason** [comment]
Right, this isn't the bug I thought it was (the one whose test I linked).

I'm pretty sure this will be a configuration issue. I don't have a reproduction from you so for now please see this similar issue [question(config): how to pin local packages to "workspace:*"?](https://github.com/JamieMason/syncpack/issues/189) particularly [this comment](https://github.com/JamieMason/syncpack/issues/189#issuecomment-1880146015).

**Comment by sibelius** [comment]
how can I keep the `workspace:*`
