### ISSUE TITLE
TypeError: (0 , minimatch_1.minimatch) is not a function

### ISSUE THREAD

**Issue by donhcd** [JamieMason/syncpack#199]
## Description

`yarn run syncpack list-mismatches` and other commands all fail due to `TypeError: (0 , minimatch_1.minimatch) is not a function`
<img width="909" alt="image" src="https://github.com/JamieMason/syncpack/assets/902007/ec392246-66ba-4014-8036-0e7ca9dfd8ef">

When I look at the code referenced by this, at `node_modules/syncpack/dist/guards/can-add-to-group.js`, I see this:
<img width="766" alt="image" src="https://github.com/JamieMason/syncpack/assets/902007/7bd4a94e-174f-417c-a247-6990f51d3707">

~I don't understand why this code is in the package -- is `(0, minimatch_1.minimatch)` ever expected to be callable? Is there something I'm doing wrong here that is causing me to end up in this bad code path?~ it seems like the comma operator essentially means that the parenthesized expression evaluates to the value of the last expression in the set of commas, so the comma thing is actually fine, but the code is broken because it should be referencing the capital `minimatch_1.Minimatch`. If I update the two cases of `minimatch_1.minimatch` it to instead be `minimatch_1.Minimatch`, I no longer get this error

## Suggested Solution

change `minimatch_1.minimatch` to `minimatch_1.Minimatch`?

**Comment by donhcd** [comment]
Thanks @JamieMason ! we had a `resolution` pinning `minimatch` to a much older version than what `syncpack` was requiring; removing that fixed the issue.

**Comment by JamieMason** [comment]
Great, glad it's all sorted 👍
