### ISSUE TITLE
Yarn workspaces support

### ISSUE THREAD

**Issue by Yzrsah** [JamieMason/syncpack#20]
It would be great if syncpack could work with yarn workspaces to help synchronize package versions across workspaces. A syncpack command specifying the root package.json could automatically use globs for workspaces.

**Comment by JamieMason** [comment]
Thanks @Yzrsah, there is similar support for lerna so adding Yarn workspaces support should hopefully be fairly approachable to you. The function that would need changing is [`getSources`](https://github.com/JamieMason/syncpack/blob/4.4.2/src/lib/get-packages.ts#L7-L17) and its test suite is at [/src/lib/get-packages.spec.ts](https://github.com/JamieMason/syncpack/blob/4.4.2/src/lib/get-packages.spec.ts#L7-L48), it is tested as an implementation detail of `getPackages`.

Your tests I think would need to mock out a package.json file which contains Yarn's `workspaces` property and assert that `getPackages` returns the expected package.json files.
