### ISSUE TITLE
How are customTypes created?

### ISSUE THREAD

**Issue by atrofimov-sc** [JamieMason/syncpack#201]
## Description

syncpack.js

```javascript
/** @type {import('syncpack').RcFile} */
const config = {
  customTypes: {
    optional: {
      path: 'optionalDependencies',
      strategy: 'versionsByName',
    },
  },
  semverGroups: [
    {
      label: 'Use caret (^) ranges for optional dependencies',
      range: '^',
      dependencyTypes: ['optional' ],
      dependencies: ['**'], 
      packages: ['**'], 
    },
  ],
};

module.exports = config;
```

And then I have a package.json

```json
{
  /* snip */
  "optionalDependencies": {
    "@sentry/utils": "*",
  }
}
```

and I'm expecting it to complain that `*` doesn't match the required range of `^`.

But it says everything is fine.

```
= Use caret (^) ranges for optional dependencies ===============================
✓ 1 valid
```

## Suggested Solution

:shrug:

## Help Needed

:shrug:

**Comment by JamieMason** [comment]
Hey @atrofimov-sc, please see the first example on the [`customTypes` docs](https://jamiemason.github.io/syncpack/config/custom-types/), points 2 and 3.

**Comment by mctrafik** [comment]
I see. For others who're finding this confusing in the documentation, the solution is to specify the `dependencyTypes` twice, in the root and in the semver. I.e.

```typescript
/** @type {import('syncpack').RcFile} */
const config = {
  customTypes: {
    optional: {
      path: 'optionalDependencies',
      strategy: 'versionsByName',
    },
  },
  dependencyTypes: ['optional'], // <=== This was missing.
  semverGroups: [
    {
      label: 'Use caret (^) ranges for optional dependencies',
      range: '^',
      dependencyTypes: ['optional'],
      dependencies: ['**'], 
      packages: ['**'], 
    },
  ],
};

module.exports = config;
```

**Comment by JamieMason** [comment]
Thanks @mctrafik, if you have time please submit some edits to the Docs – with my being so close to the implementation maybe I'll gloss over some things, it can happen.

**Comment by mctrafik** [comment]
Sure: https://github.com/JamieMason/syncpack/pull/202
