### ISSUE TITLE
`syncpack format` orders dependencies differently than npm does

### ISSUE THREAD

**Issue by jenseng** [JamieMason/syncpack#206]
## Description

`syncpack format` orders dependencies differently than npm does, so package.json can easily become "unformatted" every time you install a new package (npm likes to re-sort things). This is most noticeable if a dependency begins with a number (e.g. `5to6-codemod`); syncpack will sort it before any scoped deps (presumably because of [this](https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/bin-format/format.ts#L89)), whereas npm puts scoped deps first (since it uses `localeCompare` when sorting).

Basic repro:
- `npm i 5to6-codemod @babel/register`
- Note that `@babel/register` appears **_before_** `5to6-codemod` in package.json
- `npx syncpack format`
- Note that `@babel/register` now appears **_after_** `5to6-codemod`
- `npm i @babel/types`
- Note that `@babel/*` again appears **_before_** `5to6-codemod`
- `npx syncpack lint` fails linting

While you can mostly work around this by running `syncpack format` in a pre-commit hook, this isn't always feasible (e.g. if you have automated processes that are updating packages ... in that case those also need to explicitly run `syncpack format`)

## Suggested Solution

`syncpack` should sort dependencies the same way that npm does (using a `localeCompare`-based sort, rather than a vanilla sort)

**Comment by JamieMason** [comment]
_Great_ spot @jenseng, thanks a lot. 

Syncpack is just doing a completely basic `.sort()` which I wrongly thought would be enough, thanks for pointing this out.

https://github.com/JamieMason/syncpack/blob/db2b31ccdb1a28fdbe0c42d27ce956ea5c6c543a/src/bin-format/format.ts#L120C10-L126

**Comment by JamieMason** [comment]
Released in [12.4.0](https://github.com/JamieMason/syncpack/releases/tag/12.4.0)

**Comment by bruce-c-liu** [comment]
@JamieMason Perhaps this is out of scope of syncpack (it's unclear if it's only intended to support npm), but I think pnpm uses a vanilla sort?

e.g. pnpm creates these entries in package.json, but syncpack format doesn't like it:
"string-hash": "1.1.3",
"string_decoder": "1.3.0",

**Comment by JamieMason** [comment]
Hey @bruce-c-liu, there is a discussion at [question(format): do all package managers sort fields in the same order?](https://github.com/JamieMason/syncpack/issues/286#issuecomment-2993725530)
