### ISSUE TITLE
fix(config): add `$schema` property as optional string

### ISSUE THREAD

**Issue by turbocrime** [JamieMason/syncpack#207]
## Description

1. create any valid syncpack config json
2. add `"$schema": "https://unpkg.com/syncpack@12.3.0/dist/schema.json"` to your config
3. the schema fails to validate due to the presence of a `$schema` field

## Suggested Solution

include `"$schema": { "type": "string" }` in your schema properties

**Comment by JamieMason** [comment]
Thanks @turbocrime 👍

**Comment by JamieMason** [comment]
Released in [12.4.0](https://github.com/JamieMason/syncpack/releases/tag/12.4.0)
