### ISSUE TITLE
Feature request: Manage .npmignore files

### ISSUE THREAD

**Issue by dalgard** [JamieMason/syncpack#21]
Thanks for the good work. A feature I've been missing is the ability to manage the `.npmignore` files in each package.

NPM doesn't walk upwards in the folder structure, so it is more or less mandatory to have an `.npmignore` file in every package. Being able to check, sync, or update them would make the situation feel less insecure.

I hope you will consider this added feature. Thanks again.

**Comment by JamieMason** [comment]
Thanks @dalgard, this sounds pretty useful.

One thing that would really help would be to go into detail on what the feature would ideally look like from an end-user point of view:

- What would the commands ideally be called? 
- What would they do?
- What options might they take?
- What generic behaviour might not always be desirable? What might be a good way of handling those scenarios if they arise?

Thanks a lot!
