### ISSUE TITLE
syncpack is "updating" the version field of a local package.json

### ISSUE THREAD

**Issue by 6XGate** [JamieMason/syncpack#212]
## Description

I initialized a node project using a name called `wing`. This is an internal project that will never be published, but does collide with an existing npm package. It's version is set to "0.0.1" and has a workspace of other projects.

Every time I run `syncpack`, it tries to "update" the project itself by adjusting that version number. This project is set to private in the package.json and is not related.

Can't find any way to prevent syncpack from "damaging" my local packages' meta data.

## Suggested Solution

Remove or add a means to disable this functionality.

**Comment by 6XGate** [comment]
Okay, it's worse than I thought, it does that to every package.json in the project. And if you specify a version group that does a pinVersion on $LOCAL, it will replace every package's version with that pinVersion.

**Comment by JamieMason** [comment]
Don't talk to me like that, fix your scare quotes and the other nonsense and I'll happily help you out. It can all be resolved with your config but I'm not helping you with your tone as it is.

**Comment by 6XGate** [comment]
I'll apologize if this is really considered a hostile tone, but it was not the intent. I also don't appreciate the obvious hostile tone out right and that would not go over well in a professional environment.

While the tool seems to work pretty good, this behavior does not seem like a reasonable default.
I did manage to fix this by listing everything but `"version"` via `"dependencyTypes": ["dev", "overrides", "peer", "pnpmOverrides", "prod", "resolutions"],`.
