### ISSUE TITLE
question(config): how to provide custom config file?

### ISSUE THREAD

**Issue by turbocrime** [JamieMason/syncpack#217]
- add an "indent" field to your `syncpack.config.json` that is not the default of two spaces
- call `syncpack format`
- observe that your package.jsons are formatted with two-space indentation

**Comment by JamieMason** [comment]
`syncpack.config.json` is not one of the recognised filenames which are auto-discovered, but it can be provided using the `--config` option, please see the [Configuration File](https://jamiemason.github.io/syncpack/config/syncpackrc/) docs.
