### ISSUE TITLE
Config file example from the docs doesn't have proper types because of the missing types export

### ISSUE THREAD

**Issue by maksnester** [JamieMason/syncpack#219]
## Description

This is what the experience looks like in WebStorm IDE before and after adding the "types" export.

https://github.com/JamieMason/syncpack/assets/4989157/16e37f40-1c85-4e06-b138-a132210fde94

## Suggested Solution

https://github.com/JamieMason/syncpack/pull/218

**Comment by JamieMason** [comment]
Great issue, and thanks a lot for the PR to fix 🎉
