### ISSUE TITLE
question(config): how to pin local packages to "workspace:*"? (3)

### ISSUE THREAD

**Issue by johtso** [JamieMason/syncpack#230]
I get output like this:

```
= Use workspace protocol when developing local packages ========================
✘ my-package 0.0.0 → workspace:* services/my-package/package.json > version [PinnedMismatch]
```

I'd understand that pinned versions in dependencies pointing to other packages in your monorepo should be changed to "workspace:*", but `"version": "workspace:*"` for a package doesn't make sense.

Using syncpack 12.3.3

Am I doing something wrong?

**Comment by JamieMason** [comment]
Hi @johtso,
I can't see your config file but I think you might need to remove the `local` dependency type from being included in your rule.

https://jamiemason.github.io/syncpack/guide/local-package-versions/#the-local-dependency-type

**Comment by johtso** [comment]
Thanks @JamieMason 

I have this in my config, but I guess that's not quite right:

```json
{
  "versionGroups": [
    {
      "label": "Use workspace protocol when developing local packages",
      "dependencies": ["$LOCAL"],
      "pinVersion": "workspace:*"
    }
  ]
}
```

**Comment by JamieMason** [comment]
Great, I think [this fix](https://github.com/JamieMason/syncpack/issues/189#issuecomment-1880146015) should do it 👍

**Comment by johtso** [comment]
> Great, I think [this fix](https://github.com/JamieMason/syncpack/issues/189#issuecomment-1880146015) should do it 👍

Ah amazing! I fell into the same trap 😂 

Thanks for the help

**Comment by JamieMason** [comment]
You're welcome, lots of people get caught by this one 😁
