### ISSUE TITLE
Anyway to disable scripts sorting?

### ISSUE THREAD

**Issue by HommeSauvage** [JamieMason/syncpack#233]
## Description

I would like to have syncpack format my package.json but not touch the scripts part. Reason is, we have lots of scripts and we have a specific order for those for readability.

## Suggested Solution

Add `sortScripts: boolean` to the config

**Comment by HommeSauvage** [comment]
It's in `sortAz`

**Comment by JamieMason** [comment]
Thanks @HommeSauvage 👍
