### ISSUE TITLE
v12.4.0 is broken on Node 18

### ISSUE THREAD

**Issue by ColinCee** [JamieMason/syncpack#237]
## Description

1. Use node 18.19.0
2. Try to install syncpack `yarn install syncpack`
3. Get error: `error minimatch@10.0.1: The engine "node" is incompatible with this module. Expected version "20 || >=22". Got "18.19.0"`

## Suggested Solution

1. Revert to minimatch v9
2. Considering this is a breaking change this should probably be a major version no?

**Comment by JamieMason** [comment]
Thanks @ColinCee,
The 12.4.0 tag [passed CI on Node.js 18.x](https://github.com/JamieMason/syncpack/actions/runs/10072453057/job/27844418675) so I wasn't aware. That is using pnpm, I can look at adding other CI jobs to check installation with other package managers, to see if that would catch engines regressions in the future.

**Comment by ColinCee** [comment]
Thanks Jamie, very interesting that pnpm is passing whilst yarn isn't. 

Note the project I'm working on is using yarn v1 which I know is not ideal

**Comment by JamieMason** [comment]
It's all good, a lot of people still use Yarn v1 – I still have it on a lot of projects.

**Comment by JamieMason** [comment]
Hopefully fixed in [13.0.0](https://github.com/JamieMason/syncpack/releases/tag/13.0.0)
