### ISSUE TITLE
How to add `**` to `source` for any package.json?

### ISSUE THREAD

**Issue by guillempuche** [JamieMason/syncpack#245]
## Description

I want Syncpack to look for any package.json inside `xiroi-apps` folder.

```js
	source: [
		'package.json',
		'xiroi-packages/**/package.json',
	],
```

**Comment by JamieMason** [comment]
That looks right to me @guillempuche, is your config file being picked up by syncpack? Try running with `SYNCPACK_VERBOSE=true syncpack lint`

**Comment by guillempuche** [comment]
Great, seems working.
