### ISSUE TITLE
Don't require .version in package.json files.

### ISSUE THREAD

**Issue by therockstorm** [JamieMason/syncpack#247]
## Description

I use Nx and `nx release`. From [their documentation](https://nx.dev/recipes/nx-release/publish-custom-dist-directory#use-file-or-workspace-references-and-do-not-track-versions-in-source-control), I should remove `version` from `package.json` files. However, doing so gives me the following error on syncpack v13.0.0:

```
npx syncpack lint
Formatting
✓ package.json
Versions
= Default Version Group ========================================================
    58 ✓ already valid
Semver Ranges
= the version property of package.json files must always be exact ==============
✘ name @clipboard-health/core-utils or version PACKAGE_JSON_HAS_NO_VERSION are not supported package.json > version [UnsupportedMismatch]
= Semver Group 2 ===============================================================
✓ 52 valid
```

I've tried adding the following to the config, but still get the error:
```json
{
  "semverGroups": [
    {
      "dependencies": [
        "**"
      ],
      "dependencyTypes": [
        "local"
      ],
      "isIgnored": true,
      "packages": [
        "**"
      ],
      "range": ""
    }
  ]
}
```

The only way to get around it is to add `"lintSemverRanges": false,`, but I'd like to be able to lint other ranges.

## Suggested Solution

Don't require `version` in `package.json` files.

**Comment by JamieMason** [comment]
Hey @therockstorm, I've not tried to do this before, but give this a go:

```json
{
  "dependencyTypes": ["!local"]
}
```

or failing that, try:

```json
{
  "semverGroups": [
    {
      "dependencyTypes": ["local"],
      "isIgnored": true
    }
  ],
  "versionGroups": [
    {
      "dependencyTypes": ["local"],
      "isIgnored": true
    }
  ]
}
```

Some thoughts:

- Your example had both `range` and `isIgnored` defined, that should've complained about it not being clear which of the two you wanted. I'll look into that.
- Maybe you also needed to ignore local packages under `versionGroups`.

See how that goes, otherwise some changes could be needed to syncpack, thanks.

**Comment by therockstorm** [comment]
Thanks for the quick response! This still gives the error:
```
{
  "semverGroups": [
    {
      "dependencyTypes": [
        "local"
      ],
      "isIgnored": true
    },
    {
      "range": "",
      "dependencyTypes": [
        "dev",
        "prod",
        "resolutions"
      ],
      "dependencies": [
        "**"
      ],
      "packages": [
        "**"
      ]
    }
  ],
  "versionGroups": [
    {
      "dependencyTypes": [
        "local"
      ],
      "isIgnored": true
    },
    {
      "dependencyTypes": [
        "peer"
      ],
      "specifierTypes": "range"
    }
  ]
}
```

But adding `"dependencyTypes": ["!local"]` to the top-level works, thanks!

**Comment by JamieMason** [comment]
Phew, I thought I had a problem until I read to the end 😂
