### ISSUE TITLE
question: pinVersion in all packages except excluded

### ISSUE THREAD

**Issue by wyozi** [JamieMason/syncpack#250]
### Question

Hi! I would like to pin a dependency to a specific version in all packages except the ones specified, i.e. something like

```
"packages": [
  "!onsite",
  "**"
],
```

Is this possible?

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/JamieMason/syncpack/blob/main/CODE_OF_CONDUCT.md)

**Comment by JamieMason** [comment]
Hey Joonas, yes that should work – you can also omit the `'**'`

```json
{
  "versionGroups": [
    {
      "dependencies": ["!onsite"],
      "pinVersion": "18.14.2"
    }
  ]
}
```

**Comment by wyozi** [comment]
ah, nice. The example I used in my message did not seem to work (`fix-mismatches` changed the excluded packages) but your example does. Thanks!

**Comment by JamieMason** [comment]
My guess is probably the '**' caused syncpack to include every package 👍
