### ISSUE TITLE
feature: allow for custom sorting for fix-mismatches

### ISSUE THREAD

**Issue by fzxt** [JamieMason/syncpack#40]
## Description

Expected usecase: 
using prerelease / experimental react versions should sync correctly (`0.0.0-experimental-b53ea6ca0`), i.e, imagine going from 16.12.0 to an experimental version, you now want to sync the experimental version across all your package versions in your monorepo when using the `fix-mismatches` command.

Actual: 
package changes are marked as mismatched, stable version is taken (`16.12.0`)

```diff
+        "react": "^16.12.0",
+       "react-dom": "^16.12.0",
-        "react": "^0.0.0-experimental-b53ea6ca0",
-        "react-dom": "^0.0.0-experimental-b53ea6ca0",
```

Peeking at the source code, i see there is some logic for taking the _newest_ version, which uses the `semver` package,
which I guess could be an issue since React doesn't use semantic versioning, and instead uses `0.0.0-sha`.

## Suggested Solution

Admittedly, not too sure on what the API would look like. Would like to have some discussion on the issue first.

One possible approach is to accept a flag to take the lowest version for a specific package, e.g. `--take-lowest react`. As we iterate through the synced packages, we take the reversed ordering.

Another one is to provide a way to specify a custom comparator to the sorting functions.

## Help Needed
- Mostly seeking discussion on whether this is something `syncpack` would be open to a PR for
- If so, iterate on the API.

**Comment by JamieMason** [comment]
hey @fzxt thanks for your patience, it's been a busy few weeks. I'm not sure either really what to do about this and, like you, whether on balance it'd be a good idea to add something in for it. I'm open to discussing it further but at the moment I don't think this will be a good fit – when you're working with experimental software you run into things like this and I don't really want them to bleed into this project.

See what you think, I'm open to hearing your thoughts and am prepared to change my mind.

Thanks a lot.

**Comment by fzxt** [comment]
Hi @JamieMason, I think that's fair -- thanks for the reply.  Feel free to close this issue for now, since I do think it's a bit esoteric and specific to `react`.

**Comment by JamieMason** [comment]
Thanks @fzxt, appreciate it.
