### ISSUE TITLE
versionGroups not working with multiple elements

### ISSUE THREAD

**Issue by JasonGore** [JamieMason/syncpack#43]
## Description

I'm not sure if I'm using this feature correctly, but `versionGroups` is an array type which seems to imply it supports multiple entries. It works fine when I have one entry, but as soon as I add a second entry, it actually seems to break BOTH entries.

1. Clone https://github.com/JasonGore/repro-syncpack
2. `yarn`
3. `yarn repro`

### Expected: 

No syncpack errors.

### Actual: 

Syncpack seems to ignore `versionGroups` and errors:

```
λ yarn repro
yarn run v1.22.4
$ syncpack list-mismatches --prod --dev
✕ fs-extra
- 9.0.1 in dependencies of syncpack-repro-a
- 9.0.1 in dependencies of syncpack-repro-c
- 9.0.1 in dependencies of syncpack-repro-a
- 8.0.1 in dependencies of syncpack-repro-b
- 9.0.1 in dependencies of syncpack-repro-c
✕ node-fetch
- 2.6.1 in dependencies of syncpack-repro-a
- 2.6.1 in dependencies of syncpack-repro-c
- 2.6.1 in dependencies of syncpack-repro-a
- 2.4.1 in dependencies of syncpack-repro-b
- 2.6.1 in dependencies of syncpack-repro-c
✕ uuid
- 6.0.0 in dependencies of syncpack-repro-a
- 8.3.0 in dependencies of syncpack-repro-c
- 6.0.0 in dependencies of syncpack-repro-a
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If you just delete the second entry `versionGroups` in `package.json` from:

```
    "versionGroups": [
      {
        "dependencies": ["fs-extra", "node-fetch"],
        "packages": ["syncpack-repro-b"]
      },
      {
        "dependencies": ["uuid"],
        "packages": ["syncpack-repro-c"]
      }
    ]
```

to:
```
    "versionGroups": [
      {
        "dependencies": ["fs-extra", "node-fetch"],
        "packages": ["syncpack-repro-b"]
      }
    ]
```

Then you actually see some of the errors resolving:

```
λ yarn repro
yarn run v1.22.4
$ syncpack list-mismatches --prod --dev
✕ uuid
- 6.0.0 in dependencies of syncpack-repro-a
- 8.3.0 in dependencies of syncpack-repro-c
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I would expect both entries to work based on the type, but beyond that, it actually seems like the second entry breaks both entries.

**Comment by JamieMason** [comment]
Thanks @JasonGore, I will take a look.

**Comment by JamieMason** [comment]
Had a look last night and I'm not too far off a fix, it'll take a me a few days mainly due to availability. One issue in the repro is that there are no sources, `source` is an empty array in the config and there are none passed via CLI options. This has uncovered another issue I should fix around falling back to the defaults.

**Comment by JamieMason** [comment]
Released in [5.6.10](https://github.com/JamieMason/syncpack/releases/tag/5.6.10) 🤞 

Thanks for the handy repro, I have converted it into a test to catch any regressions: https://github.com/JamieMason/syncpack/blob/f4cb055845139be8f210ce1f992fa8e847311c80/src/commands/lib/installations/get-grouped-mismatched-dependencies.spec.ts#L217-L245

Please let me know if you run into any more problems, thanks.

**Comment by JasonGore** [comment]
It worked perfectly for my actual use case, which has 12 entries. Thanks for the quick fix!

**Comment by JamieMason** [comment]
That's great. You're welcome
