### ISSUE TITLE
discuss: how to fix non-semver dependencies

### ISSUE THREAD

**Issue by jaybowong** [JamieMason/syncpack#45]
## Description

I have a monorepo that contains 3 react-native apps.
Before running `fix-mismatches`
```
// apps/a/package.json
"dependencies": {
  "@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-a-bug",
}

// apps/b/package.json
"dependencies": {
  "@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-another-bug",
}
```
After
```
// apps/a/package.json
"dependencies": {
  "@react-native-community/cameraroll": "1.3.1",
}

// apps/b/package.json
"dependencies": {
  "@react-native-community/cameraroll": "1.3.1",
}
```

It changes the custom URL dependency back to the original one, which is not expected.

Not sure if anyone else has the same situation like this.

## Suggested Solution

The situation above is a little bit complicated and we just don't have a clue to fix it automatically. Only the developer can solve it.
My suggestion is that syncpack skips those custom URL dependencies and give warnings in the console to let developers know that there are problems to solve, like:
```
// console output

Warnings: the dependencies below need sync manually.
- apps/a/package.json -> "@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-a-bug"
- apps/b/package.json -> "@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-another-bug"
```

**Comment by ryuuji3** [comment]
I just ran up against this problem as well, we're using a namespaced package where we had to fork one of our dependencies.
eg.
```json
{
 "next": "npm:@organization/next@version" 
}
```

became:

```json
{
 "next": "^version" 
}
```

I would be able to automatically fix mismatches if not for this problem. Really appreciate this package though, and wouldn't mind contributing.

**Comment by JamieMason** [comment]
Thanks both, this definitely needs doing but I'm busy with some private projects. I will get to it and/or am of course happy to merge PRs.

**Comment by JamieMason** [comment]
I've just been having a look at this but have a few questions.

For

```
"@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-a-bug"
```

and

```
"@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-another-bug"
```

to both become

```
"@react-native-community/cameraroll": "1.3.1"
```

means that one of the packages in your workspace depends on

```
"@react-native-community/cameraroll": "1.3.1"
```

Can you tell me a bit more about the situations you're in @jaybowong and @ryuuji3? What causes you to have this kind of mix? I ask to understand it better and so I don't put something in for this which causes unexpected changes in other user's projects.

This applies to both @jaybowong and @ryuuji3's comments, if you could give me some more context that'd be great.

Thanks

**Comment by jaybowong** [comment]
@JamieMason 

The monorepo has three react-native apps. 
One of the apps(A) has dependency "@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-a-bug", added by me. 
Another one(B) has "@react-native-community/cameraroll": "https://github.com/my-fork/react-native-cameraroll.git#fix-another-bug", added by one of my colleagues. Of course he might not know what I did with A until Syncpack tells him.

Syncpack is the perfect tool to find problems like this. What we want to do is to avoid multiple versions of @react-native-community/cameraroll because it's a react-native dependency that contains native code(Objective-C, Swift, Java, Kotlin, etc.). We don't use no-hoist because it is hard to maintain. So there's only one copy of the native code, either `fix-a-bug` or `fix-another-bug`, as a result, either A or B may use the wrong native code, even worse, can't compile.

What we usually do is to merge the two branches into one, which can fix both bugs. And then we move on with the single copy of the native code. We also do PRs if possible so that we can use "@react-native-community/cameraroll": "1.3.1" again because it's so much easier to maintain.

When custom url dependencies are involved, it would be convenient to just leave them and report warnings, instead of changing them to the official ones.

**Comment by JamieMason** [comment]
Sorry @jaybowong I'm still not quite clear, 
The only way syncpack would set the version to `"1.3.1"` is if one of the package.json files which syncpack inspected  had a version of `"1.3.1"`. 

If the only two versions in the entire monorepo are `https://github.com/my-fork/react-native-cameraroll.git#fix-a-bug` and `https://github.com/my-fork/react-native-cameraroll.git#fix-another-bug` syncpack would just ignore it on this line:

https://github.com/JamieMason/syncpack/blob/8bf31c8e5d85f70b74c132b0457533f7d4c57fc2/src/commands/fix-mismatches.ts#L26

The tests for how the version is chosen are here:

https://github.com/JamieMason/syncpack/blob/8bf31c8e5d85f70b74c132b0457533f7d4c57fc2/src/commands/lib/get-highest-version.spec.ts

I'm happy to help but at the moment I need some more help to understand, thanks.

**Comment by JamieMason** [comment]
Closing as stale
