### ISSUE TITLE
Use workspace's packages version as source of truth in fix-mismatches

### ISSUE THREAD

**Issue by remorses** [JamieMason/syncpack#47]
## Description

When doing `fix-mismatches` it would be cool to sync dependencies version to use the local version, taken from the `package.json` version field instead of using the higher version found in the deps tree

## Suggested Solution

Use the package.json version field of workspace packages as  a range present in the dependency tree

**Comment by JamieMason** [comment]
Should be there for you in 5.7.11 @remorses, thanks.
