### ISSUE TITLE
fix: globs starting with ./ resolve to undefined name in output

### ISSUE THREAD

**Issue by Aghassi** [JamieMason/syncpack#49]
## Description

I'm using the `syncpack.config.js` as my rc file for one reason: our monorepo doesn't have a standard `packages/` folder, so I'm listing paths by hand. As such, my `source` array looks like this:

```js
  source: [
    // Root package.json
    '.',
    'path/to/package,
  ].map(entry => `${entry}/package.json`),
```

When an error is found against the path `./package.json` (root package.json) the name assigned to it is `undefined`. I assume the code is stripping out `/package.json` and trying to use what comes before it, which in this case has no name.

Example:
```
Error, package mismatch found:
x webpack-cli

3.3.12 in dependencies of undefined
^3.3.11 in dependencies of package
```

## Suggested Solution

If no path before `/package.json`, just return `package.json` or `root`.
 

## Help Needed

Knowing where the paths are sanitized in the code, other than that I can probably do the fix.

**Comment by JamieMason** [comment]
Slow reply here @Aghassi, I think the problem will be in this function:

https://github.com/JamieMason/syncpack/blob/8bf31c8e5d85f70b74c132b0457533f7d4c57fc2/src/commands/lib/get-wrappers.ts#L68

In your case those glob patterns will be in `program.source` and be picked up by `getCliPatterns` on this line:

https://github.com/JamieMason/syncpack/blob/8bf31c8e5d85f70b74c132b0457533f7d4c57fc2/src/commands/lib/get-wrappers.ts#L80

If you could add a failing test to https://github.com/JamieMason/syncpack/blob/8bf31c8e5d85f70b74c132b0457533f7d4c57fc2/src/commands/lib/get-wrappers.spec.ts and submit a fix that would be a huge help.

Thanks for reporting this.

**Comment by JamieMason** [comment]
Being a little lazy here @Aghassi but can you check this is still the case in [6.0.0](https://github.com/JamieMason/syncpack/releases/tag/6.0.0)?

**Comment by Aghassi** [comment]
I don't know why I missed this but we upgraded to 6.x.x and I didn't test. I will check now that we also updated to 7.x
