### ISSUE TITLE
feat: apply constraints to versions used when fixing mismatches

### ISSUE THREAD

**Issue by vjpr** [JamieMason/syncpack#53]
I have a bunch of packages using webpack@4 and webpack@5. I basically want all packages to pin to the same version of either 4 or 5 depending on what they currently depend on.

Some packages depend on `webpack@5.0.0-beta.18` for example. This is because it was the only package available at the time, but now I want them all to use the latest.

I guess its similar to `versionGroups`, but instead of listing `packages`, I want to list the semver range for the group.

Something like:

```json
{
  "versionGroups": [
    {
      "dependencies": ["webpack"],
      "versions": ["webpack@4<5"],
    },
    {
      "dependencies": ["webpack"],
      "versions": ["webpack@>5"],
    }
  ]
}
```

**Comment by JamieMason** [comment]
It's been a long time getting around to this, but how does this sound @vjpr?

- `@old-stuff/*` must have the same versions of `webpack`, `lodash`, and `react`
- `@new-stuff/*` must have the same versions of `webpack`, `lodash`, and `react`
- `@old-stuff/*` and `@new-stuff/*` can have different versions of `webpack`, `lodash`, and `react` to each other
- `lodash` and `react` mismatches will always be synced to the newest version found
- `webpack` within `@old-stuff/*` will be synced to to the newest version which matches the constraint `webpack@<5`
- `webpack` within `@new-stuff/*` will be synced to to the newest version which matches the constraint `webpack@>5`
- If no version matches the constraint, throw an error and quit

```json
{
  "versionGroups": [
    {
      "dependencies": ["webpack", "lodash", "react"],
      "packages": ["@old-stuff/server","@old-stuff/ui"],
      "constraints": ["webpack@<5"]
    },
    {
      "dependencies": ["webpack", "lodash", "react"],
      "packages": ["@new-stuff/server","@new-stuff/ui"],
      "constraints": ["webpack@>5"]
    }
  ]
}
```

**Comment by JamieMason** [comment]
Shall I close this one @vjpr?

**Comment by JamieMason** [comment]
This should now be possible in [6.1.0](https://github.com/JamieMason/syncpack/releases/tag/6.1.0).
