### ISSUE TITLE
feat: format - option to opt out of sorting specific properties

### ISSUE THREAD

**Issue by myrddraall** [JamieMason/syncpack#55]
## Description

Sometime an objects properties need to remain in the order they are set. 
for example when using `npm-rull-all` in sequential mode  it runs the scripts in the order that they are defined

I do understand that this could be achieved with the configuration file, so its a "nice to have"  

```
"scripts": {
    "build": "run-s build:* ",
    "build:clean": "...",
    "build:anotherStep": "...",
 },
```

when you run `yarn build`, the scripts are executed in the order
1. build:clean
1. build:anotherStep

after running `format` the order is changed to 
1. build:anotherStep
1. build:clean

## Suggested Solution

add a --skip-sort flag that takes a property path which turns off sorting of the sub-properties of the specified object

example: 
`syncpack format --skip-sort scripts`
`syncpack format --skip-sort some.custom.prop`

**Comment by JamieMason** [comment]
Thanks for raising this @myrddraall. 

Leaving a note incase anyone else stumbles on this issue, you can achieve this by overriding the default configuration of `sortAz` to not include `scripts`:

```diff
{
  "dev": true,
  "filter": ".",
  "indent": "  ",
  "peer": true,
  "prod": true,
  "semverRange": "",
-  "sortAz": ["contributors", "dependencies", "devDependencies", "keywords", "peerDependencies", "scripts"],
+  "sortAz": ["contributors", "dependencies", "devDependencies", "keywords", "peerDependencies"],
  "sortFirst": ["name", "description", "version", "author"],
  "source": ["package.json", "packages/*/package.json"],
  "versionGroups": []
}
```

**Comment by airtonix** [comment]
@JamieMason I've done what you suggested but i still see that script entries being resorted

**Comment by airtonix** [comment]
typo

![sigh-parks-and-rec](https://user-images.githubusercontent.com/61225/163077741-847830c5-86d3-45c0-9fbe-15ed4b97b1d5.gif)



`s/sortAZ/sortAz/`
