### ISSUE TITLE
Use workspace's dependencies versions as source of truth in fix-mismatches

### ISSUE THREAD

**Issue by bompus** [JamieMason/syncpack#57]
## Description

When running fix-mismatches in a folder containing a pnpm workspace, it always uses the highest version found in any of the packages, instead of the version specified in the workspace root, which I personally use as the source of truth for shared external dependencies.

## Suggested Solution
I'd like a setting to prefer the dependencies versions listed in the workspace's root package.json, instead of the highest version found in any of the workspace projects. This allows quick dependencies / devDependencies / peerDependencies version downgrades across an entire workspace by simply updating the root package.json and then running fix-mismatches.

**Comment by JamieMason** [comment]
At first I didn't think this was already a feature, but while working on [6.0.0](https://github.com/JamieMason/syncpack/releases/tag/6.0.0) I saw that this should already be the case:

https://github.com/JamieMason/syncpack/blob/fd7ef19b1babb571805e275778cdf0ef7ea111d9/src/bin-fix-mismatches/fix-mismatches.ts#L27-L29

Please give [6.0.0](https://github.com/JamieMason/syncpack/releases/tag/6.0.0) a try and reopen this issue if this does indeed need adding. 

Thanks a lot.

**Comment by chbdetta** [comment]
How does this work again? I am using an npm workspace and it doesn't use my root package.json as the source of truth

**Comment by JamieMason** [comment]
I think at the time I misread your request as being reporting a bug in
--workspace, where we use the versions of packages developed in your
monitor as the source of truth. I think I realise now what you're asking
for is the snapTo feature. If you follow
https://github.com/JamieMason/syncpack/issues/87 you can track progress.

> How does this work again? I am using an npm workspace and it doesn't use
> my root package.json as the source of truth
>
