### ISSUE TITLE
Add resolutions field to package.json dependency checking

### ISSUE THREAD

**Issue by Aghassi** [JamieMason/syncpack#60]
## Description

I can probably help with this (amongst my other issues, I swear I haven't forgotten). Essentially, right now we check `devDependencies`, `dependencies`, and `peerDependencies`. But there is also `resolutions` which can override versions all the way down the stack. It would be useful to check that too to make sure it doesn't drift either

## Suggested Solution

Support `overrides` for NPM (https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md) and `resolutions` for yarn (https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)

Add anything listed there to the list of things to compare across package.json files

## Help Needed

I think this can be done in `list-mismatches` command, but I'm not sure if there is somewhere else I should be looking. Other than that, I can't imagine this is a massive lift.

**Comment by JamieMason** [comment]
Released in [6.0.0](https://github.com/JamieMason/syncpack/releases/tag/6.0.0), thanks a lot for contributing.
