### ISSUE TITLE
Blows away line endings in every package.json file with CRLF

### ISSUE THREAD

**Issue by Zamiell** [JamieMason/syncpack#76]
Hello! And thanks for the excellent tool.

From a Windows machine, running `syncpack fix-mismatches` on my monorepo replaces the line endings in every package.json file with CRLF. (They were LF before.)

This is not good, as it breaks `prettier --check` and subsequently breaks CI.

Can the tool just copy the existing line endings that are used in the file? Or failing that, always just use LF or something?

**Comment by JamieMason** [comment]
I'm working on Windows support and this will be fixed as part of that, thanks for posting.

**Comment by Zamiell** [comment]
Thanks Jamie, appreciate it.

**Comment by Zamiell** [comment]
Hey Jamie, can I submit a PR to get this done sooner?

**Comment by JamieMason** [comment]
Proposed fix released in [8.2.4](https://github.com/JamieMason/syncpack/releases/tag/8.2.4)

**Comment by Zamiell** [comment]
Woot, thank you!
