### ISSUE TITLE
feature: show path to package.json instead of package.json name field

### ISSUE THREAD

**Issue by Aghassi** [JamieMason/syncpack#79]
## Description

When there are multiple offenders, it can be hard to align offending packages with their name field
because that is not an easily searchable.

## Suggested Solution

Show the path to the offending package.json instead of the name field

## Help Needed

Happy to help contribute this. I haven't looked into it yet. I just keep hitting it and getting annoyed :)

**Comment by JamieMason** [comment]
Sounds good, it's looking like this so far:

![Screenshot](https://user-images.githubusercontent.com/320492/171970017-eccb7904-5675-4c2f-aa49-ec28f588878d.png)

It looks a lot busier but it's better than you can easily open each file, any ideas or amends?

**Comment by Aghassi** [comment]
Yeah i think that's a good starting point

**Comment by JamieMason** [comment]
Proposed fix released in [8.2.4](https://github.com/JamieMason/syncpack/releases/tag/8.2.4)
