### ISSUE TITLE
Question: is there a way to use this with custom package directories?

### ISSUE THREAD

**Issue by rosswarren** [JamieMason/syncpack#8]
Both Lerna and Yarn Workspaces allow you to override their package directories. In our project, we are using multiple package directories. Is there a way to pass in this pattern? Alternatively would you agree to this library detecting Lerna / Yarn Workspaces and using their configuration by default to find this?

**Comment by JamieMason** [comment]
Sorry @rosswarren, I've managed to somehow miss the notification for this issue. You can define the paths to your package.json files like so:

```bash
syncpack list './package.json' './packages/*/package.json'
```

The values above are the defaults but they can be changed to anything else. You can also pass as many glob patterns as you need. I will improve the docs for `syncpack` soon as they're currently no good.

**Comment by JamieMason** [comment]
Just released [3.0.0](https://github.com/JamieMason/syncpack/blob/master/CHANGELOG.md#300-2018-08-25) which changes the above slightly:

> ### BREAKING CHANGES
> 
> Previously the location of package.json files could be overridden like so:
> 
> ```
> syncpack list './package.json' './packages/*/package.json'
> ```
> 
> This is now done using a repeatable `--source` option:
> 
> ```
> syncpack list --source './package.json' --source './packages/*/package.json'
> ```
> 
> This change is to make way for new commands which will also require an
> overridable `--target` option.
– https://github.com/JamieMason/syncpack/blob/master/CHANGELOG.md#300-2018-08-25

And the [readme](https://github.com/JamieMason/syncpack) has been updated a little too.
