### ISSUE TITLE
It seems package.json files are written even if not changed

### ISSUE THREAD

**Issue by mxro** [JamieMason/syncpack#80]
## Description

When running `syncpack` git seems to pick up that all `package.json` files have been changed. Even if there are no changes made to the files:

![image](https://user-images.githubusercontent.com/1448524/171949982-3cd3d407-6df8-4583-8872-2975bc297204.png)

## Suggested Solution

Ensure that `package.json` files are only written when they are actually changed.

**Comment by JamieMason** [comment]
Possibly related to #76 but haven't looked in detail yet 👍🏻

**Comment by JamieMason** [comment]
Please let me know if this still happens when using [8.2.4](https://github.com/JamieMason/syncpack/releases/tag/8.2.4), I think the problem was line endings.
