### ISSUE TITLE
Can’t get `semverRange` to work

### ISSUE THREAD

**Issue by AkimaLunar** [JamieMason/syncpack#89]
## Description

I have ranges in peer dependencies in my library, so wanted to use the `--semver-range` flag, as described in [syncpack#semverrange](https://github.com/JamieMason/syncpack#semverrange).

If I use a CLI flag I get an error.
```sh
syncpack --semver-range list-mismatches | fix-mismatches
```

```
error: unknown option '--semver-range'
```

Or if I use a config in my `package.json` it doesn’t seem to work.

```
  "syncpack": {
    "semverRange": ["<=", ">="],
  },
```

## Suggested Solution

To sync ranges in dependencies.

## Help Needed

Am I not using this feature right?

**Comment by JamieMason** [comment]
Hi Ria,
On mobile just now but I think you just need to swap the option and command name, here are some examples from the readme 👍

```
# uses defaults for resolving packages
syncpack set-semver-ranges
# uses packages defined by --source when provided
syncpack set-semver-ranges --source "apps/*/package.json"
# multiple globs can be provided like this
syncpack set-semver-ranges --source "apps/*/package.json" --source "core/*/package.json"
# uses dependencies regular expression defined by --filter when provided
syncpack set-semver-ranges --filter "typescript|tslint"
# use ~ range instead of default ""
syncpack set-semver-ranges --semver-range ~
# set ~ range in "devDependencies"
syncpack set-semver-ranges --dev --semver-range ~
# set ~ range in "devDependencies" and "peerDependencies"
syncpack set-semver-ranges --dev --peer --semver-range ~
# indent package.json with 4 spaces instead of 2
syncpack set-semver-ranges --indent "    "
```

I can try and help some more if you're still stuck.

**Comment by AkimaLunar** [comment]
Hmm, I am still getting the same error:

```bash
> syncpack list-mismatches --semver-range

error: unknown option '--semver-range'

> syncpack list-mismatches --semver-range <= >=

error: unknown option '--semver-range'
```

**Comment by JamieMason** [comment]
Try `syncpack set-semver-ranges --semver-range "<="`

**Comment by AkimaLunar** [comment]
That gives me another error 😅

```
➜ npx syncpack set-semver-ranges --semver-range "<="
/home/riacarmin/Projects/arbutus/node_modules/syncpack/dist/bin-set-semver-ranges/set-semver-ranges.js:18
                root[dependencyType][name] = nextVersion;
                                           ^

TypeError: Cannot set properties of undefined (setting '[PACKAGE_NAME]')
```

I am not sure `set-semver-ranges` is the command I need though based on this description, but maybe I am wrong!

> Ensure dependency versions used within "dependencies", "devDependencies", and "peerDependencies" follow a consistent format.

My peer dependencies look like this:

```json
  "peerDependencies": {
    "react": ">=16.8.0 <=18.2.0",
    "react-dom": ">=16.8.0 <=18.2.0"
  },
```
If I run `find|fix-mismatches` those dependencies get flagged and changed to ^.

```bash
✘ react >=16.8.0 <=18.2.0, ^17.0.2
✘ react-dom >=16.8.0 <=18.2.0, ^17.0.2
```
So I disabled peers in the `package.json` for now:

```json
  "syncpack": {
    "semverRange": [
      "<=",
      ">="
    ],
    "workspace": true,
    "peer": false ⬅️
  },
```

But ideally I would like to keep them in sync instead. So I like the format! More so if one package get changed to `<=18.3.0` I can easily propagate the upgraded range across monorepo.

**Comment by JamieMason** [comment]
No problem Ria, let's walk through it:

There are two parts to this, the first is where to find help about what each command and option do:

1. For any command you can see instructions by adding `--help`
1. If we run `syncpack list-mismatches --help` we will see that the `list-mismatches` command doesn't take a `--semver-range` option.
1. If you run `syncpack --help` we see a list of all commands available.
1. We see that `set-semver-ranges` and `lint-semver-ranges` deal with semver ranges.
1. Let's see if `syncpack lint-semver-ranges --help` can help us
1. `lint-semver-ranges` does accept a `--semver-range` option
1. We also see a list of all the valid values you can use with `--semver-range`
1. If we go to the [readme](https://github.com/JamieMason/syncpack) there is documentation for syncpack
1. There's a [section about the semverRange option](https://github.com/JamieMason/syncpack#semverrange) we're trying to use.
1. Adding more than one semverRange is not possible
1. We can set it to a string but not an array of values.
   ```diff
   - "semverRange": [
   -   "<=",
   -   ">="
   - ],
   + "semverRange": "^",
   ```

The second part is that versions like `">=16.8.0 <=18.2.0"` aren't understood by syncpack - and I can completely see why this has got you confused – the word range normally means like a range of numbers or something `1` to `10`, or a range of versions like you have here `>=16.8.0` to `<=18.2.0`. So why isn't syncpack letting me set a range (ie. multiple values) for the semverRange property?

Ok, what syncpack means by "semverRange" is the characters to the left of the version number which decide how strict or how loose the version matching should be, here are examples of every one:

| range | example |
| ----- | ------- |
| <     | <1.4.2  |
| <=    | <=1.4.2 |
| ""    | 1.4.2   |
| ~     | ~1.4.2  |
| ^     | ^1.4.2  |
| >=    | >=1.4.2 |
| >     | >1.4.2  |
| \*    | \*      |

Your situation where the "version value" contains more than one "version" ie. ``">=16.8.0 <=18.2.0"`` is more complex to handle and is not supported.

I can see why in your scenario the term "semver range" will be confusing.

Let me know if this makes sense so far and we can go from there.

**Comment by AkimaLunar** [comment]
Thanks for the explanation, @JamieMason! I will keep the peers disabled for now then.

**Comment by JamieMason** [comment]
Any problems just shout 👍
