### ISSUE TITLE
Use of "within" in documentation is ambiguous

### ISSUE THREAD

**Issue by benjaminhobbs** [JamieMason/syncpack#90]
## Description

The repo's documentation is a little more ambiguous than it needs to be. Particularly the word "within" is used extensively; in some places, it'd be clearer to directly say what is being compared "between" and what is "within".

For example, 

"You don't want mismatches within your alpha packages, you don't want mismatches within the other packages, but you do want those groups to use different versions to each other and not have syncpack make them all the same."

## Suggested Solution

Rewrite docs

**Comment by JamieMason** [comment]
Thanks @benjaminhobbs, will take a look and revise.

**Comment by JamieMason** [comment]
Started applying this a little in the [docs site](https://jamiemason.github.io/syncpack/), using between instead. I'll close this but please feel free to raise any others like it, or submit PRs via the "edit this page" links. I'll be filling out the new docs site over the next few weeks.

Thanks a lot for helping improve the docs.
